In [1]:
# %matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

# Loading Raw Data

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train[:, 0:27, 0:27]
x_test = x_test[:, 0:27, 0:27]

In [3]:
x_train_flatten = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])/255.0
x_test_flatten = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])/255.0

In [4]:
print(x_train_flatten.shape, y_train.shape)
print(x_test_flatten.shape, y_test.shape)

(60000, 729) (60000,)
(10000, 729) (10000,)


In [5]:
x_train_0 = x_train_flatten[y_train == 0]
x_train_1 = x_train_flatten[y_train == 1]
x_train_2 = x_train_flatten[y_train == 2]
x_train_3 = x_train_flatten[y_train == 3]
x_train_4 = x_train_flatten[y_train == 4]
x_train_5 = x_train_flatten[y_train == 5]
x_train_6 = x_train_flatten[y_train == 6]
x_train_7 = x_train_flatten[y_train == 7]
x_train_8 = x_train_flatten[y_train == 8]
x_train_9 = x_train_flatten[y_train == 9]

x_train_list = [x_train_0, x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6, x_train_7, x_train_8, x_train_9]

print(x_train_0.shape)
print(x_train_1.shape)
print(x_train_2.shape)
print(x_train_3.shape)
print(x_train_4.shape)
print(x_train_5.shape)
print(x_train_6.shape)
print(x_train_7.shape)
print(x_train_8.shape)
print(x_train_9.shape)

(5923, 729)
(6742, 729)
(5958, 729)
(6131, 729)
(5842, 729)
(5421, 729)
(5918, 729)
(6265, 729)
(5851, 729)
(5949, 729)


In [6]:
x_test_0 = x_test_flatten[y_test == 0]
x_test_1 = x_test_flatten[y_test == 1]
x_test_2 = x_test_flatten[y_test == 2]
x_test_3 = x_test_flatten[y_test == 3]
x_test_4 = x_test_flatten[y_test == 4]
x_test_5 = x_test_flatten[y_test == 5]
x_test_6 = x_test_flatten[y_test == 6]
x_test_7 = x_test_flatten[y_test == 7]
x_test_8 = x_test_flatten[y_test == 8]
x_test_9 = x_test_flatten[y_test == 9]

x_test_list = [x_test_0, x_test_1, x_test_2, x_test_3, x_test_4, x_test_5, x_test_6, x_test_7, x_test_8, x_test_9]

print(x_test_0.shape)
print(x_test_1.shape)
print(x_test_2.shape)
print(x_test_3.shape)
print(x_test_4.shape)
print(x_test_5.shape)
print(x_test_6.shape)
print(x_test_7.shape)
print(x_test_8.shape)
print(x_test_9.shape)

(980, 729)
(1135, 729)
(1032, 729)
(1010, 729)
(982, 729)
(892, 729)
(958, 729)
(1028, 729)
(974, 729)
(1009, 729)


# Selecting the dataset

Output: X_train, Y_train, X_test, Y_test

In [7]:
n_train_sample_per_class = 200
n_class = 4

X_train = x_train_list[0][:n_train_sample_per_class, :]
Y_train = np.zeros((X_train.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_train = np.concatenate((X_train, x_train_list[i+1][:n_train_sample_per_class, :]), axis=0)
    Y_train[(i+1)*n_train_sample_per_class:(i+2)*n_train_sample_per_class] = i+1

X_train.shape, Y_train.shape

((800, 729), (800,))

In [8]:
n_test_sample_per_class = int(0.25*n_train_sample_per_class)

X_test = x_test_list[0][:n_test_sample_per_class, :]
Y_test = np.zeros((X_test.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_test = np.concatenate((X_test, x_test_list[i+1][:n_test_sample_per_class, :]), axis=0)
    Y_test[(i+1)*n_test_sample_per_class:(i+2)*n_test_sample_per_class] = i+1

X_test.shape, Y_test.shape

((200, 729), (200,))

# Dataset Preprocessing

In [9]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((800, 27, 27), (200, 27, 27))

In [10]:
Y_train_dict = []
for i in range(np.unique(Y_train).shape[0]):
    temp_Y = np.zeros(Y_train.shape)
    
    temp_Y[Y_train == i] = 0  # positive class
    temp_Y[Y_train != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_train_dict += [('Y' + str(i), temp_Y)]
    
Y_train_dict = dict(Y_train_dict)

In [11]:
Y_test_dict = []
for i in range(np.unique(Y_test).shape[0]):
    temp_Y = np.zeros(Y_test.shape)
    
    temp_Y[Y_test == i] = 0  # positive class
    temp_Y[Y_test != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_test_dict += [('Y' + str(i), temp_Y)]
    
Y_test_dict = dict(Y_test_dict)

In [12]:
Y_train_dict['Y1'].shape, Y_test_dict['Y0'].shape

((800, 2), (200, 2))

# Quantum

In [13]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer, GradientDescentOptimizer

qml.enable_tape()

from tensorflow.keras.utils import to_categorical

# Set a random seed
np.random.seed(2020)

In [14]:
# Define output labels as quantum state vectors
def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return state * np.conj(state).T


label_0 = [[1], [0]]
label_1 = [[0], [1]]
state_labels = [label_0, label_1]

In [15]:
dm_labels = [density_matrix(state_labels[i]) for i in range(2)]
dm_labels

[tensor([[1, 0],
         [0, 0]], requires_grad=True),
 tensor([[0, 0],
         [0, 1]], requires_grad=True)]

In [16]:
dm_labels[0]

tensor([[1, 0],
        [0, 0]], requires_grad=True)

In [17]:
n_qubits = 2
dev_fc = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs = [x, y]
        x (array[float]): 1-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]


In [18]:
dev_conv = qml.device("default.qubit", wires=3)


@qml.qnode(dev_conv)
def q_conv(conv_params, inputs):
    """A variational quantum circuit representing the Universal classifier + Conv.

    Args:
        params (array[float]): array of parameters
        x (array[float]): 2-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    # layer iteration
    for l in range(len(conv_params[0])):
        # qubit iteration
        for q in range(3):
            qml.Rot(*(conv_params[0][l][3*q:3*(q+1)] * inputs[q, 0:3] + conv_params[1][l][3*q:3*(q+1)]), wires=q)

    return [qml.expval(qml.PauliZ(j)) for j in range(3)]

In [19]:
a = np.zeros((2, 1, 9))
q_conv(a, X_train[0, 0:3, 0:3])

tensor([1., 1., 1.], requires_grad=True)

In [20]:
a = np.zeros((2, 1, 9))
q_fc(a, X_train[0, 0, 0:9])

tensor([1., 0.], requires_grad=True)

In [21]:
from keras import backend as K

# Addition Custom Layer
def add_matrix(x):
    return K.sum(x, axis=1, keepdims=True)
    
addition_layer = tf.keras.layers.Lambda(add_matrix, output_shape=(1,))

class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [22]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(3), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(3), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)

model = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])

In [23]:
for i in range(len(Y_train_dict)):
    new_key = model.layers[len(model.layers)-4+i].name
    old_key = "Y" + str(i)
    
    Y_train_dict[new_key] = Y_train_dict.pop(old_key)
    Y_test_dict[new_key] = Y_test_dict.pop(old_key)

In [24]:
Y_train_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_1': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_2': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_3': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32)}

In [25]:
Y_test_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0.

In [26]:
model(X_train[0:5, :, :])

[<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[0.04740664, 0.00625119],
        [0.04738189, 0.00626851],
        [0.04716605, 0.00641954],
        [0.04730186, 0.00632451],
        [0.04739274, 0.00626092]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[0.01999552, 0.00714913],
        [0.01993002, 0.00722188],
        [0.01982304, 0.00734069],
        [0.0198535 , 0.00730685],
        [0.02004413, 0.00709515]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.00520818, -0.04667789],
        [-0.0051577 , -0.04688282],
        [-0.00507462, -0.04722006],
        [-0.00521916, -0.04663329],
        [-0.00518285, -0.04678069]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[ 0.00944274, -0.01021785],
        [ 0.00956372, -0.01018421],
        [ 0.00955619, -0.01018631],
        [ 0.00963773, -0.01016363],
        [ 0.00938297, -0.01023447]], dtype=float32)>]

In [27]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 27, 27)]     0                                            
__________________________________________________________________________________________________
tf.__operators__.getitem (Slici (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_1 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_2 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
______________________________________________________________________________________________

In [28]:
losses = {
    model.layers[len(model.layers)-4+0].name: "mse",
    model.layers[len(model.layers)-4+1].name: "mse",
    model.layers[len(model.layers)-4+2].name: "mse",
    model.layers[len(model.layers)-4+3].name: "mse"
}

#lossWeights = {"Y0": 1.0, "Y1": 1.0, "Y2": 1.0, "Y3": 1.0}

print(losses)

{'class_weights': 'mse', 'class_weights_1': 'mse', 'class_weights_2': 'mse', 'class_weights_3': 'mse'}


In [35]:
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.1,
    decay_steps=int(len(X_train)/32),
    decay_rate=0.95,
    staircase=True)

In [36]:
opt = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
model.compile(opt, loss=losses, metrics=["accuracy"])

In [38]:
cp_val_acc = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv1_QFC2_Branch_valacc.hdf5",
                monitor='val_accuracy', verbose=1, save_weights_only=True, save_best_only=True, mode='max')

cp_val_loss = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv1_QFC2_Branch_valloss.hdf5",
                monitor='val_loss', verbose=1, save_weights_only=True, save_best_only=True, mode='min')

In [39]:
H = model.fit(X_train, Y_train_dict, epochs=20, batch_size=32,
              validation_data=(X_test, Y_test_dict), verbose=1, initial_epoch=10,
              callbacks=[cp_val_acc, cp_val_loss])

Epoch 11/20
25/25 [==============================] - 10331s 414s/step - loss: 0.4988 - class_weights_loss: 0.0810 - class_weights_1_loss: 0.0864 - class_weights_2_loss: 0.2046 - class_weights_3_loss: 0.1269 - class_weights_accuracy: 0.9053 - class_weights_1_accuracy: 0.9066 - class_weights_2_accuracy: 0.7019 - class_weights_3_accuracy: 0.8408 - val_loss: 0.3091 - val_class_weights_loss: 0.0514 - val_class_weights_1_loss: 0.0520 - val_class_weights_2_loss: 0.1200 - val_class_weights_3_loss: 0.0857 - val_class_weights_accuracy: 0.9550 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.8250 - val_class_weights_3_accuracy: 0.8900



Epoch 00011: val_loss improved from inf to 0.30913, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 12/20
25/25 [==============================] - 10120s 405s/step - loss: 0.2766 - class_weights_loss: 0.0608 - class_weights_1_loss: 0.0321 - class_weights_2_loss: 0.1193 - class_weights_3_loss: 0.0644 - class_weights_accuracy: 0.9203 - class_weights_1_accuracy: 0.9674 - class_weights_2_accuracy: 0.8415 - class_weights_3_accuracy: 0.9350 - val_loss: 0.2765 - val_class_weights_loss: 0.0466 - val_class_weights_1_loss: 0.0339 - val_class_weights_2_loss: 0.1195 - val_class_weights_3_loss: 0.0765 - val_class_weights_accuracy: 0.9350 - val_class_weights_1_accuracy: 0.9550 - val_class_weights_2_accuracy: 0.8350 - val_class_weights_3_accuracy: 0.9050



Epoch 00012: val_loss improved from 0.30913 to 0.27645, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 13/20
25/25 [==============================] - 9845s 394s/step - loss: 0.2060 - class_weights_loss: 0.0335 - class_weights_1_loss: 0.0234 - class_weights_2_loss: 0.0907 - class_weights_3_loss: 0.0583 - class_weights_accuracy: 0.9649 - class_weights_1_accuracy: 0.9792 - class_weights_2_accuracy: 0.8862 - class_weights_3_accuracy: 0.9300 - val_loss: 0.2542 - val_class_weights_loss: 0.0676 - val_class_weights_1_loss: 0.0360 - val_class_weights_2_loss: 0.0967 - val_class_weights_3_loss: 0.0539 - val_class_weights_accuracy: 0.9100 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8700 - val_class_weights_3_accuracy: 0.9600



Epoch 00013: val_loss improved from 0.27645 to 0.25416, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 14/20
25/25 [==============================] - 9880s 396s/step - loss: 0.2272 - class_weights_loss: 0.0379 - class_weights_1_loss: 0.0312 - class_weights_2_loss: 0.0999 - class_weights_3_loss: 0.0582 - class_weights_accuracy: 0.9548 - class_weights_1_accuracy: 0.9727 - class_weights_2_accuracy: 0.8819 - class_weights_3_accuracy: 0.9419 - val_loss: 0.3212 - val_class_weights_loss: 0.0559 - val_class_weights_1_loss: 0.0851 - val_class_weights_2_loss: 0.1186 - val_class_weights_3_loss: 0.0616 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9050 - val_class_weights_2_accuracy: 0.8450 - val_class_weights_3_accuracy: 0.9200



Epoch 00014: val_loss did not improve from 0.25416
Epoch 15/20
25/25 [==============================] - 9937s 398s/step - loss: 0.2766 - class_weights_loss: 0.0333 - class_weights_1_loss: 0.0611 - class_weights_2_loss: 0.1142 - class_weights_3_loss: 0.0680 - class_weights_accuracy: 0.9609 - class_weights_1_accuracy: 0.9177 - class_weights_2_accuracy: 0.8511 - class_weights_3_accuracy: 0.9090 - val_loss: 0.2673 - val_class_weights_loss: 0.0391 - val_class_weights_1_loss: 0.0542 - val_class_weights_2_loss: 0.0994 - val_class_weights_3_loss: 0.0747 - val_class_weights_accuracy: 0.9650 - val_class_weights_1_accuracy: 0.9400 - val_class_weights_2_accuracy: 0.8750 - val_class_weights_3_accuracy: 0.9050



Epoch 00015: val_loss did not improve from 0.25416
Epoch 16/20
25/25 [==============================] - 9904s 397s/step - loss: 0.2256 - class_weights_loss: 0.0417 - class_weights_1_loss: 0.0242 - class_weights_2_loss: 0.1009 - class_weights_3_loss: 0.0588 - class_weights_accuracy: 0.9497 - class_weights_1_accuracy: 0.9784 - class_weights_2_accuracy: 0.8705 - class_weights_3_accuracy: 0.9267 - val_loss: 0.3452 - val_class_weights_loss: 0.0928 - val_class_weights_1_loss: 0.0318 - val_class_weights_2_loss: 0.1531 - val_class_weights_3_loss: 0.0676 - val_class_weights_accuracy: 0.8750 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.7600 - val_class_weights_3_accuracy: 0.8950



Epoch 00016: val_loss did not improve from 0.25416
Epoch 17/20
25/25 [==============================] - 10011s 401s/step - loss: 0.2502 - class_weights_loss: 0.0654 - class_weights_1_loss: 0.0355 - class_weights_2_loss: 0.0932 - class_weights_3_loss: 0.0560 - class_weights_accuracy: 0.9084 - class_weights_1_accuracy: 0.9686 - class_weights_2_accuracy: 0.8653 - class_weights_3_accuracy: 0.9306 - val_loss: 0.2315 - val_class_weights_loss: 0.0411 - val_class_weights_1_loss: 0.0332 - val_class_weights_2_loss: 0.0864 - val_class_weights_3_loss: 0.0708 - val_class_weights_accuracy: 0.9650 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.9100 - val_class_weights_3_accuracy: 0.8950



Epoch 00017: val_loss improved from 0.25416 to 0.23151, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 18/20
25/25 [==============================] - 9981s 400s/step - loss: 0.2225 - class_weights_loss: 0.0404 - class_weights_1_loss: 0.0288 - class_weights_2_loss: 0.0940 - class_weights_3_loss: 0.0593 - class_weights_accuracy: 0.9477 - class_weights_1_accuracy: 0.9738 - class_weights_2_accuracy: 0.8680 - class_weights_3_accuracy: 0.9265 - val_loss: 0.2242 - val_class_weights_loss: 0.0349 - val_class_weights_1_loss: 0.0306 - val_class_weights_2_loss: 0.0836 - val_class_weights_3_loss: 0.0751 - val_class_weights_accuracy: 0.9700 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.9100



Epoch 00018: val_loss improved from 0.23151 to 0.22424, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 19/20
25/25 [==============================] - 10247s 411s/step - loss: 0.2157 - class_weights_loss: 0.0369 - class_weights_1_loss: 0.0226 - class_weights_2_loss: 0.0931 - class_weights_3_loss: 0.0630 - class_weights_accuracy: 0.9614 - class_weights_1_accuracy: 0.9776 - class_weights_2_accuracy: 0.8896 - class_weights_3_accuracy: 0.9244 - val_loss: 0.2196 - val_class_weights_loss: 0.0495 - val_class_weights_1_loss: 0.0252 - val_class_weights_2_loss: 0.0751 - val_class_weights_3_loss: 0.0697 - val_class_weights_accuracy: 0.9150 - val_class_weights_1_accuracy: 0.9800 - val_class_weights_2_accuracy: 0.9200 - val_class_weights_3_accuracy: 0.9150



Epoch 00019: val_loss improved from 0.22424 to 0.21955, saving model to ./Model/4_QConv1_QFC2_Branch_valloss.hdf5
Epoch 20/20
25/25 [==============================] - 10250s 410s/step - loss: 0.1931 - class_weights_loss: 0.0336 - class_weights_1_loss: 0.0254 - class_weights_2_loss: 0.0773 - class_weights_3_loss: 0.0568 - class_weights_accuracy: 0.9616 - class_weights_1_accuracy: 0.9749 - class_weights_2_accuracy: 0.9098 - class_weights_3_accuracy: 0.9435 - val_loss: 0.2227 - val_class_weights_loss: 0.0281 - val_class_weights_1_loss: 0.0247 - val_class_weights_2_loss: 0.0878 - val_class_weights_3_loss: 0.0821 - val_class_weights_accuracy: 0.9750 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.8950



Epoch 00020: val_loss did not improve from 0.21955


In [40]:
# next 10 epochs (lr=lr_decay)
H.history

{'loss': [0.43470999598503113,
  0.2671163082122803,
  0.22298204898834229,
  0.23815858364105225,
  0.23344069719314575,
  0.22885894775390625,
  0.2591063976287842,
  0.23571200668811798,
  0.22658871114253998,
  0.19660954177379608],
 'class_weights_loss': [0.07047296315431595,
  0.060057345777750015,
  0.03757486864924431,
  0.04201560840010643,
  0.03502611070871353,
  0.034103892743587494,
  0.061428967863321304,
  0.03639243543148041,
  0.03910483047366142,
  0.0350370779633522],
 'class_weights_1_loss': [0.06793732941150665,
  0.031770091503858566,
  0.028540685772895813,
  0.03876782953739166,
  0.04229447990655899,
  0.029790904372930527,
  0.03389740362763405,
  0.036986831575632095,
  0.028510570526123047,
  0.023634184151887894],
 'class_weights_2_loss': [0.1761278659105301,
  0.11319337785243988,
  0.09734311699867249,
  0.09541252255439758,
  0.09538803994655609,
  0.10307004302740097,
  0.10145143419504166,
  0.09738997370004654,
  0.09822680801153183,
  0.0830864906311

In [32]:
# first 10 epochs (lr=0.1)
H.history

{'loss': [0.9569375514984131,
  0.5365726947784424,
  0.45871007442474365,
  0.4279939532279968,
  0.346034437417984,
  0.29439547657966614,
  0.28186529874801636,
  0.26313525438308716,
  0.24418294429779053,
  0.23212386667728424],
 'class_weights_loss': [0.2079225331544876,
  0.09608516097068787,
  0.07941573113203049,
  0.07548997551202774,
  0.05834708362817764,
  0.044848546385765076,
  0.043818388134241104,
  0.048248134553432465,
  0.0341222919523716,
  0.03289236128330231],
 'class_weights_1_loss': [0.22261661291122437,
  0.0663885846734047,
  0.05435347184538841,
  0.06591470539569855,
  0.05138702318072319,
  0.040870413184165955,
  0.04013250395655632,
  0.03876625746488571,
  0.0349545031785965,
  0.032074932008981705],
 'class_weights_2_loss': [0.2697601914405823,
  0.1996682733297348,
  0.19040939211845398,
  0.16775798797607422,
  0.14148356020450592,
  0.1276315450668335,
  0.11278621852397919,
  0.10952628403902054,
  0.10712245851755142,
  0.09726810455322266],
 'cla

In [57]:
model.save_weights('./Model/4_QConv1_QFC2_Branch_last.hdf5')

In [41]:
# next 10 epochs (lr=lr_decay)
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.5038777 , -0.86366093,  1.2798227 ,  0.4467905 ,
           1.3563266 , -1.6452367 , -0.15417844, -0.6304267 ,
           0.09601111],
         [ 1.1907735 , -0.6694465 , -0.31650114, -1.2320808 ,
           0.5369861 ,  0.02890281, -0.06313864,  0.8152295 ,
           0.01167965]],
 
        [[-0.47499505,  0.6915185 ,  0.6082095 ,  0.38401112,
          -1.0388781 , -0.07887959, -0.24697499,  1.4532354 ,
           0.3481095 ],
         [-0.3679892 , -0.72441095,  0.03221685, -0.03238652,
           0.90667605,  0.07754139, -0.28177896,  1.7780479 ,
          -0.47317278]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.36387172, -0.23979254, -0.46985844,  0.32103962,
           1.2570168 ,  0.50424474,  0.13179208,  0.42834753,
           1.088595  ],
         [-0.716924  ,  0.2699094 ,  0.3398109 ,

In [34]:
# first 10 epochs (lr=0.1)
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.5078843 , -0.64590204,  1.3205096 ,  0.4493004 ,
           1.2040567 , -1.7244085 , -0.15329137, -0.23616321,
           0.09100989],
         [ 0.94592625, -0.8108717 , -0.314886  , -1.3123106 ,
           0.64961845,  0.030234  , -0.0459107 ,  0.9051824 ,
           0.01041241]],
 
        [[-0.47833568,  0.63722193,  0.50517726,  0.38695082,
          -0.99613065, -0.21469879, -0.24638735,  1.0187893 ,
           0.26552266],
         [-0.47102186, -0.63769835,  0.03166989, -0.16820548,
           1.041123  ,  0.0750619 , -0.36436638,  1.3671039 ,
          -0.47114694]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.36304605, -0.08742111, -0.5516954 ,  0.33058712,
           1.024965  ,  0.43893006,  0.12608829,  0.6266899 ,
           0.99202347],
         [-0.6951818 ,  0.3003292 ,  0.34953773,

# Result Analysis

In [58]:
model.load_weights('./Model/4_QConv1_QFC2_Branch_valloss.hdf5')

In [59]:
test_res = model.predict(X_test)
train_res = model.predict(X_train)

In [60]:
def ave_loss(class_pred):
    return ((class_pred[0] - 1)**2 + (class_pred[1] - 0)**2)

In [61]:
# max pred prob value

train_pred = np.zeros((len(train_res[0]), ))

# samples loop
for i in range(len(train_res[0])):
    temp_max = 0
    class_max = None
    
    # class loop
    for j in range(4):
        # check positive class
        if temp_max < train_res[j][i][0]:
            temp_max = train_res[j][i][0]
            class_max = j
            
    train_pred[i] = class_max

In [62]:
((Y_train == train_pred).sum())/(len(train_pred))

tensor(0.8925, requires_grad=True)

In [63]:
# min loss value

train_pred = np.zeros((len(train_res[0]), ))

# samples loop
for i in range(len(train_res[0])):
    temp_min = 100
    class_min = None
    
    # class loop
    for j in range(4):
        # check loss value
        if temp_min > ave_loss(train_res[j][i]):
            temp_min = ave_loss(train_res[j][i])
            class_min = j
            
    train_pred[i] = class_min

In [64]:
((Y_train == train_pred).sum())/(len(train_pred))

tensor(0.89, requires_grad=True)

In [ ]:
# method of determining true class


# weights after 10 epochs lr decay
# highest positive value: train 0.905, test 0.875
# lowest mse: train 0.905, test 0.875


# best val loss weights
# highest positive value: train 0.8925, test 0.895
# lowest mse: train 0.89, test 0.895

In [69]:
# max pred prob value

test_pred = np.zeros((len(test_res[0]), ))

# samples loop
for i in range(len(test_res[0])):
    temp_max = 0
    class_max = None
    
    # class loop
    for j in range(4):
        # check positive class
        if temp_max < test_res[j][i][0]:
            temp_max = test_res[j][i][0]
            class_max = j
            
    test_pred[i] = class_max

In [70]:
((Y_test == test_pred).sum())/(len(test_pred))

tensor(0.895, requires_grad=True)

In [71]:
# best val loss weights
# highest pred proba
# wrong test sample

np.where((Y_test == test_pred) == False)[0]

array([ 12,  37,  58, 103, 109, 111, 118, 120, 122, 124, 134, 137, 142,
       150, 161, 168, 181, 189, 191, 193, 197])

In [72]:
# min loss value

test_pred = np.zeros((len(test_res[0]), ))

# samples loop
for i in range(len(test_res[0])):
    temp_min = 100
    class_min = None
    
    # class loop
    for j in range(4):
        # check loss value
        if temp_min > ave_loss(test_res[j][i]):
            temp_min = ave_loss(test_res[j][i])
            class_min = j
            
    test_pred[i] = class_min

In [73]:
((Y_test == test_pred).sum())/(len(test_pred))

tensor(0.895, requires_grad=True)

In [74]:
# best val loss weights
# lowest mse
# wrong test sample

np.where((Y_test == test_pred) == False)[0]

array([ 12,  37,  58, 103, 109, 111, 118, 120, 122, 124, 134, 137, 142,
       150, 161, 168, 181, 189, 191, 193, 197])

In [ ]:
array([ 29,  37, 103, 118, 120, 124, 135, 139, 150, 155, 161, 164, 168,
       172, 176, 181, 182, 185, 186, 189, 190, 191, 193, 197, 199])

# Exploring the results

In [76]:
# best val loss
model.load_weights('./Model/4_QConv1_QFC2_Branch_valloss.hdf5')
all_weights = model.get_weights()
all_weights

[array([[[-0.504826  , -0.70958436,  1.3552876 ,  0.4471665 ,
           1.3373322 , -1.8432273 , -0.15418075, -0.82940537,
           0.09094326],
         [ 1.1394029 , -0.65106654, -0.31549048, -1.3228155 ,
           0.49518916,  0.02911025, -0.11533158,  0.59447795,
           0.01175652]],
 
        [[-0.47717744,  0.85880464,  0.6799101 ,  0.38430533,
          -1.1193122 , -0.2428085 , -0.24700566,  1.3684444 ,
           0.31989387],
         [-0.29628867, -0.7246381 ,  0.03315024, -0.19631542,
           0.91714025,  0.07760317, -0.3099947 ,  1.6867847 ,
          -0.4730031 ]]], dtype=float32),
 array([[[ 0.36409384, -0.18457337, -0.44409102,  0.32283378,
           1.2514359 ,  0.41380718,  0.13083619,  0.4699626 ,
           0.90419096],
         [-0.77689004,  0.34707996,  0.33955535,  0.7000987 ,
          -1.0993775 ,  0.40713048, -0.299968  , -0.02284523,
           0.31234446]],
 
        [[ 0.18303034, -0.5726352 , -0.24218315, -0.5254779 ,
           0.949475  ,  0.

In [77]:
qconv_1_weights = all_weights[0]

qconv_1_weights.shape

(2, 2, 9)

In [78]:
qconv_2_weights = all_weights[1]

qconv_2_weights.shape

(2, 2, 9)

In [80]:
q_fc_weights_0 = all_weights[2]

q_fc_weights_1 = all_weights[3]

q_fc_weights_2 = all_weights[4]

q_fc_weights_3 = all_weights[5]

q_fc_weights_0.shape, q_fc_weights_1.shape, q_fc_weights_2.shape, q_fc_weights_3.shape

((2, 2, 9), (2, 2, 9), (2, 2, 9), (2, 2, 9))

In [81]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(3), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


qconv1_model = tf.keras.Model(inputs=X, outputs=reshape_layer_1)


qconv1_model(X_train[0:1])
qconv1_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])

In [82]:
np.isclose(qconv1_model.get_weights()[0], qconv_1_weights).sum()

tensor(36, requires_grad=True)

In [83]:
preprocessed_img_train_1 = qconv1_model(X_train)

preprocessed_img_test_1 = qconv1_model(X_test)

data_train = preprocessed_img_train_1.numpy().reshape(-1, 13*13)
np.savetxt('./4_QConv1_QFC2_Branch-Filter1_Image_Train.txt', data_train)

data_test = preprocessed_img_test_1.numpy().reshape(-1, 13*13)
np.savetxt('./4_QConv1_QFC2_Branch-Filter1_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(800, 169) (200, 169)


In [85]:
# Second Quantum Conv Layer, trainable params = 18, output size = 6 x 6

X_2 = tf.keras.Input(shape=(size_1,size_1), name='Input_Layer_2')

num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(3), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(X_2[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


qconv2_model = tf.keras.Model(inputs=X_2, outputs=reshape_layer_2)


qconv2_model(preprocessed_img_train_1[0:1])
qconv2_model.get_layer('Quantum_Conv_Layer_2').set_weights([qconv_2_weights])

In [88]:
np.isclose(qconv2_model.get_weights()[0], qconv_2_weights).sum()

tensor(36, requires_grad=True)

In [89]:
preprocessed_img_train_2 = qconv2_model(preprocessed_img_train_1)

preprocessed_img_test_2 = qconv2_model(preprocessed_img_test_1)

data_train = preprocessed_img_train_2.numpy().reshape(-1, 6*6)
np.savetxt('./4_QConv1_QFC2_Branch-Filter2_Image_Train.txt', data_train)

data_test = preprocessed_img_test_2.numpy().reshape(-1, 6*6)
np.savetxt('./4_QConv1_QFC2_Branch-Filter2_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(800, 36) (200, 36)


In [90]:
# Max Pooling Layer, output size = 9

X_3 = tf.keras.Input(shape=(size_2,size_2,1), name='Input_Layer_3')

max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(X_3)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)

maxpool_model = tf.keras.Model(inputs=X_3, outputs=reshape_layer_3)

In [91]:
maxpool_train = maxpool_model(preprocessed_img_train_2)
maxpool_test = maxpool_model(preprocessed_img_test_2)

maxpool_train.shape, maxpool_test.shape

(TensorShape([800, 9]), TensorShape([200, 9]))

In [92]:
np.savetxt('./4_QConv1_QFC2_Branch-TrainedMaxPool_Train.txt', maxpool_train)
np.savetxt('./4_QConv1_QFC2_Branch-TrainedMaxPool_Test.txt', maxpool_test)

In [93]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [94]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [95]:
# branch 0

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_0, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_0, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [96]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
 False  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True False False  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False  True  True  True  True  True  True False  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [97]:
np.savetxt('./4_0_QConv1_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_0_QConv1_QFC2_Branch-State_Test.txt', test_state)

In [98]:
# branch 1

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_1, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_1, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [99]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [100]:
np.savetxt('./4_1_QConv1_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_1_QConv1_QFC2_Branch-State_Test.txt', test_state)

In [101]:
# branch 2

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_2, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_2, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [102]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False False False False False False False False False  True
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
  True False False False False False False False False False False False
 False False False  True False False False False False False  True False
 False False False False False False  True False False False False False
 False False False False False False False False Fa

In [103]:
np.savetxt('./4_2_QConv1_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_2_QConv1_QFC2_Branch-State_Test.txt', test_state)

In [104]:
# branch 3

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_3, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_3, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [105]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False Fa

In [106]:
np.savetxt('./4_3_QConv1_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_3_QConv1_QFC2_Branch-State_Test.txt', test_state)

## Random Starting State

In [108]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(3), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(3), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)


model_random = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])
model_maxpool_random = tf.keras.Model(inputs=X, outputs=reshape_layer_3)

In [110]:
model_random(X_train[0:1])
all_random_weights = model_random.get_weights()

In [111]:
all_random_weights

[array([[[ 0.4736303 , -0.44591266, -0.3844845 ,  0.13883978,
           0.02961409, -0.31372344,  0.00663352, -0.12008744,
          -0.4799831 ],
         [-0.05830157,  0.37957358,  0.34670353, -0.50864017,
           0.2558304 ,  0.26354182, -0.5159275 , -0.05588323,
           0.32214582]],
 
        [[-0.44065022,  0.23793256,  0.27685815,  0.04750907,
           0.30202723, -0.06547448,  0.26491952,  0.04792702,
          -0.39964372],
         [ 0.26730663, -0.32680163,  0.3326475 , -0.3070858 ,
           0.44441545,  0.3604908 ,  0.33842623,  0.00972533,
          -0.1309416 ]]], dtype=float32),
 array([[[ 0.3673212 ,  0.2268092 ,  0.17581391, -0.11930826,
           0.19259912,  0.18129909, -0.23133504,  0.42894453,
           0.2578405 ],
         [ 0.04846078, -0.31858197, -0.20728955,  0.1849432 ,
          -0.4073209 , -0.17292166,  0.323663  , -0.3958016 ,
          -0.04574025]],
 
        [[-0.4035516 ,  0.189354  ,  0.33227932, -0.09922504,
          -0.38093495,  0.

In [112]:
random_weights_0 = all_random_weights[2]

random_weights_1 = all_random_weights[3]

random_weights_2 = all_random_weights[4]

random_weights_3 = all_random_weights[5]

In [113]:
maxpool_train = model_maxpool_random(X_train)
maxpool_test = model_maxpool_random(X_test)

maxpool_train.shape, maxpool_test.shape

(TensorShape([800, 9]), TensorShape([200, 9]))

In [114]:
np.savetxt('./4_QConv1_QFC2_Branch-RandomMaxPool_Train.txt', maxpool_train)
np.savetxt('./4_QConv1_QFC2_Branch-RandomMaxPool_Test.txt', maxpool_test)

In [115]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [116]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [117]:
# branch 0

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_0, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_0, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [118]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [119]:
np.savetxt('./4_0_QConv1_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_0_QConv1_QFC2_Branch-RandomState_Test.txt', test_state)

In [120]:
# branch 1

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_1, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_1, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [121]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [122]:
np.savetxt('./4_1_QConv1_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_1_QConv1_QFC2_Branch-RandomState_Test.txt', test_state)

In [123]:
# branch 2

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_2, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_2, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [124]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [125]:
np.savetxt('./4_2_QConv1_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_2_QConv1_QFC2_Branch-RandomState_Test.txt', test_state)

In [126]:
# branch 3

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_3, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_3, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [127]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [128]:
np.savetxt('./4_3_QConv1_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_3_QConv1_QFC2_Branch-RandomState_Test.txt', test_state)