In [1]:
# %matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

# Loading Raw Data

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train[:, 0:27, 0:27]
x_test = x_test[:, 0:27, 0:27]

In [3]:
x_train_flatten = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])/255.0
x_test_flatten = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])/255.0

In [4]:
print(x_train_flatten.shape, y_train.shape)
print(x_test_flatten.shape, y_test.shape)

(60000, 729) (60000,)
(10000, 729) (10000,)


In [5]:
x_train_0 = x_train_flatten[y_train == 0]
x_train_1 = x_train_flatten[y_train == 1]
x_train_2 = x_train_flatten[y_train == 2]
x_train_3 = x_train_flatten[y_train == 3]
x_train_4 = x_train_flatten[y_train == 4]
x_train_5 = x_train_flatten[y_train == 5]
x_train_6 = x_train_flatten[y_train == 6]
x_train_7 = x_train_flatten[y_train == 7]
x_train_8 = x_train_flatten[y_train == 8]
x_train_9 = x_train_flatten[y_train == 9]

x_train_list = [x_train_0, x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6, x_train_7, x_train_8, x_train_9]

print(x_train_0.shape)
print(x_train_1.shape)
print(x_train_2.shape)
print(x_train_3.shape)
print(x_train_4.shape)
print(x_train_5.shape)
print(x_train_6.shape)
print(x_train_7.shape)
print(x_train_8.shape)
print(x_train_9.shape)

(5923, 729)
(6742, 729)
(5958, 729)
(6131, 729)
(5842, 729)
(5421, 729)
(5918, 729)
(6265, 729)
(5851, 729)
(5949, 729)


In [6]:
x_test_0 = x_test_flatten[y_test == 0]
x_test_1 = x_test_flatten[y_test == 1]
x_test_2 = x_test_flatten[y_test == 2]
x_test_3 = x_test_flatten[y_test == 3]
x_test_4 = x_test_flatten[y_test == 4]
x_test_5 = x_test_flatten[y_test == 5]
x_test_6 = x_test_flatten[y_test == 6]
x_test_7 = x_test_flatten[y_test == 7]
x_test_8 = x_test_flatten[y_test == 8]
x_test_9 = x_test_flatten[y_test == 9]

x_test_list = [x_test_0, x_test_1, x_test_2, x_test_3, x_test_4, x_test_5, x_test_6, x_test_7, x_test_8, x_test_9]

print(x_test_0.shape)
print(x_test_1.shape)
print(x_test_2.shape)
print(x_test_3.shape)
print(x_test_4.shape)
print(x_test_5.shape)
print(x_test_6.shape)
print(x_test_7.shape)
print(x_test_8.shape)
print(x_test_9.shape)

(980, 729)
(1135, 729)
(1032, 729)
(1010, 729)
(982, 729)
(892, 729)
(958, 729)
(1028, 729)
(974, 729)
(1009, 729)


# Selecting the dataset

Output: X_train, Y_train, X_test, Y_test

In [208]:
n_train_sample_per_class = 200
n_class = 4

X_train = x_train_list[0][:n_train_sample_per_class, :]
Y_train = np.zeros((X_train.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_train = np.concatenate((X_train, x_train_list[i+1][:n_train_sample_per_class, :]), axis=0)
    Y_train[(i+1)*n_train_sample_per_class:(i+2)*n_train_sample_per_class] = i+1

X_train.shape, Y_train.shape

((800, 729), (800,))

In [209]:
n_test_sample_per_class = int(0.25*n_train_sample_per_class)

X_test = x_test_list[0][:n_test_sample_per_class, :]
Y_test = np.zeros((X_test.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_test = np.concatenate((X_test, x_test_list[i+1][:n_test_sample_per_class, :]), axis=0)
    Y_test[(i+1)*n_test_sample_per_class:(i+2)*n_test_sample_per_class] = i+1

X_test.shape, Y_test.shape

((200, 729), (200,))

# Dataset Preprocessing

In [210]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((800, 27, 27), (200, 27, 27))

In [211]:
Y_train_dict = []
for i in range(np.unique(Y_train).shape[0]):
    temp_Y = np.zeros(Y_train.shape)
    
    temp_Y[Y_train == i] = 0  # positive class
    temp_Y[Y_train != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_train_dict += [('Y' + str(i), temp_Y)]
    
Y_train_dict = dict(Y_train_dict)

In [212]:
Y_test_dict = []
for i in range(np.unique(Y_test).shape[0]):
    temp_Y = np.zeros(Y_test.shape)
    
    temp_Y[Y_test == i] = 0  # positive class
    temp_Y[Y_test != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_test_dict += [('Y' + str(i), temp_Y)]
    
Y_test_dict = dict(Y_test_dict)

In [213]:
Y_train_dict['Y1'].shape, Y_test_dict['Y0'].shape

((800, 2), (200, 2))

# Quantum

In [214]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer, GradientDescentOptimizer

qml.enable_tape()

from tensorflow.keras.utils import to_categorical

# Set a random seed
np.random.seed(2020)

In [215]:
# Define output labels as quantum state vectors
def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return state * np.conj(state).T


label_0 = [[1], [0]]
label_1 = [[0], [1]]
state_labels = [label_0, label_1]

In [216]:
n_qubits = 2
dev_fc = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs = [x, y]
        x (array[float]): 1-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]


In [217]:
dev_conv = qml.device("default.qubit", wires=9)


@qml.qnode(dev_conv)
def q_conv(conv_params, inputs):
    """A variational quantum circuit representing the Universal classifier + Conv.

    Args:
        params (array[float]): array of parameters
        x (array[float]): 2-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    # layer iteration
    for l in range(len(conv_params[0])):
        # RY layer
        # height iteration
        for i in range(3):
            # width iteration
            for j in range(3):
                qml.RY((conv_params[0][l][3*i+j] * inputs[i, j] + conv_params[1][l][3*i+j]), wires=(3*i+j))
    
        # entangling layer
        for i in range(9):
            if i != (9-1):
                qml.CNOT(wires=[i, i+1])

    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2) @ qml.PauliZ(3) @ qml.PauliZ(4) @ qml.PauliZ(5) @ qml.PauliZ(6) @ qml.PauliZ(7) @ qml.PauliZ(8))

In [218]:
a = np.zeros((2, 1, 9))
q_conv(a, X_train[0, 0:3, 0:3])

tensor(1., requires_grad=True)

In [219]:
a = np.zeros((2, 1, 9))
q_fc(a, X_train[0, 0, 0:9])

tensor([1., 0.], requires_grad=True)

In [220]:
class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [223]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)

model = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])

In [224]:
for i in range(len(Y_train_dict)):
    new_key = model.layers[len(model.layers)-4+i].name
    old_key = "Y" + str(i)
    
    Y_train_dict[new_key] = Y_train_dict.pop(old_key)
    Y_test_dict[new_key] = Y_test_dict.pop(old_key)

In [225]:
Y_train_dict

{'class_weights_8': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_9': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_10': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_11': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32)}

In [226]:
Y_test_dict

{'class_weights_8': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [

In [227]:
model(X_train[0:5, :, :])

[<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.06101445,  0.00124834],
        [-0.06095054,  0.00125403],
        [-0.06099783,  0.00124982],
        [-0.06091789,  0.00125693],
        [-0.06095978,  0.00125321]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[0.07227105, 0.00066544],
        [0.07266474, 0.00059932],
        [0.07246957, 0.0006321 ],
        [0.0726416 , 0.00060321],
        [0.07224991, 0.00066899]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.0730686 , -0.00077061],
        [-0.07328282, -0.00072914],
        [-0.0731007 , -0.0007644 ],
        [-0.07331893, -0.00072214],
        [-0.073041  , -0.00077596]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.03235819,  0.00869795],
        [-0.03212601,  0.00886284],
        [-0.03244124,  0.00863896],
        [-0.03240439,  0.00866514],
        [-0.03224283,  0.00877988]], dtype=float32)>]

In [228]:
model.summary()

Model: "model_5"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 27, 27)]     0                                            
__________________________________________________________________________________________________
tf.__operators__.getitem_989 (S (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_990 (S (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_991 (S (None, 3, 3)         0           Input_Layer[0][0]                
____________________________________________________________________________________________

In [229]:
losses = {
    model.layers[len(model.layers)-4+0].name: "mse",
    model.layers[len(model.layers)-4+1].name: "mse",
    model.layers[len(model.layers)-4+2].name: "mse",
    model.layers[len(model.layers)-4+3].name: "mse"
}

#lossWeights = {"Y0": 1.0, "Y1": 1.0, "Y2": 1.0, "Y3": 1.0}

print(losses)

{'class_weights_8': 'mse', 'class_weights_9': 'mse', 'class_weights_10': 'mse', 'class_weights_11': 'mse'}


In [230]:
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.1,
    decay_steps=int(len(X_train)/32),
    decay_rate=0.95,
    staircase=True)

In [231]:
opt = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
model.compile(opt, loss=losses, metrics=["accuracy"])

In [35]:
cp_val_acc = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_2QFC_valacc.hdf5",
                monitor='val_accuracy', verbose=1, save_weights_only=True, save_best_only=True, mode='max')

cp_val_loss = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_2QFC_valloss.hdf5",
                monitor='val_loss', verbose=1, save_weights_only=True, save_best_only=True, mode='min')

In [36]:
H = model.fit(X_train, Y_train_dict, epochs=10, batch_size=32,
              validation_data=(X_test, Y_test_dict), verbose=1, initial_epoch=0,
              callbacks=[cp_val_acc, cp_val_loss])

Epoch 1/10
25/25 [==============================] - 27009s 1080s/step - loss: 0.3399 - class_weights_loss: 0.0719 - class_weights_1_loss: 0.0581 - class_weights_2_loss: 0.1239 - class_weights_3_loss: 0.0859 - class_weights_accuracy: 0.9016 - class_weights_1_accuracy: 0.9302 - class_weights_2_accuracy: 0.8288 - class_weights_3_accuracy: 0.8985 - val_loss: 0.2675 - val_class_weights_loss: 0.0661 - val_class_weights_1_loss: 0.0466 - val_class_weights_2_loss: 0.0890 - val_class_weights_3_loss: 0.0658 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9550 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.9000



Epoch 00001: val_loss improved from inf to 0.26747, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 2/10
25/25 [==============================] - 27263s 1092s/step - loss: 0.2508 - class_weights_loss: 0.0596 - class_weights_1_loss: 0.0307 - class_weights_2_loss: 0.1071 - class_weights_3_loss: 0.0534 - class_weights_accuracy: 0.9293 - class_weights_1_accuracy: 0.9739 - class_weights_2_accuracy: 0.8588 - class_weights_3_accuracy: 0.9350 - val_loss: 0.2509 - val_class_weights_loss: 0.0675 - val_class_weights_1_loss: 0.0358 - val_class_weights_2_loss: 0.0902 - val_class_weights_3_loss: 0.0574 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9650 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.9200



Epoch 00002: val_loss improved from 0.26747 to 0.25092, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 3/10
25/25 [==============================] - 27457s 1100s/step - loss: 0.2248 - class_weights_loss: 0.0463 - class_weights_1_loss: 0.0359 - class_weights_2_loss: 0.0884 - class_weights_3_loss: 0.0542 - class_weights_accuracy: 0.9389 - class_weights_1_accuracy: 0.9562 - class_weights_2_accuracy: 0.8953 - class_weights_3_accuracy: 0.9382 - val_loss: 0.2500 - val_class_weights_loss: 0.0577 - val_class_weights_1_loss: 0.0409 - val_class_weights_2_loss: 0.0966 - val_class_weights_3_loss: 0.0548 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8650 - val_class_weights_3_accuracy: 0.9350



Epoch 00003: val_loss improved from 0.25092 to 0.24997, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 4/10
25/25 [==============================] - 26998s 1080s/step - loss: 0.2131 - class_weights_loss: 0.0384 - class_weights_1_loss: 0.0339 - class_weights_2_loss: 0.0968 - class_weights_3_loss: 0.0440 - class_weights_accuracy: 0.9605 - class_weights_1_accuracy: 0.9695 - class_weights_2_accuracy: 0.8854 - class_weights_3_accuracy: 0.9607 - val_loss: 0.2828 - val_class_weights_loss: 0.0580 - val_class_weights_1_loss: 0.0445 - val_class_weights_2_loss: 0.1025 - val_class_weights_3_loss: 0.0778 - val_class_weights_accuracy: 0.9300 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.8750 - val_class_weights_3_accuracy: 0.9100



Epoch 00004: val_loss did not improve from 0.24997
Epoch 5/10
25/25 [==============================] - 27116s 1087s/step - loss: 0.2285 - class_weights_loss: 0.0485 - class_weights_1_loss: 0.0377 - class_weights_2_loss: 0.0901 - class_weights_3_loss: 0.0523 - class_weights_accuracy: 0.9379 - class_weights_1_accuracy: 0.9670 - class_weights_2_accuracy: 0.8839 - class_weights_3_accuracy: 0.9346 - val_loss: 0.2941 - val_class_weights_loss: 0.0699 - val_class_weights_1_loss: 0.0338 - val_class_weights_2_loss: 0.1269 - val_class_weights_3_loss: 0.0635 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8350 - val_class_weights_3_accuracy: 0.9100



Epoch 00005: val_loss did not improve from 0.24997
Epoch 6/10
25/25 [==============================] - 27311s 1093s/step - loss: 0.2486 - class_weights_loss: 0.0465 - class_weights_1_loss: 0.0352 - class_weights_2_loss: 0.1094 - class_weights_3_loss: 0.0575 - class_weights_accuracy: 0.9417 - class_weights_1_accuracy: 0.9681 - class_weights_2_accuracy: 0.8745 - class_weights_3_accuracy: 0.9289 - val_loss: 0.2805 - val_class_weights_loss: 0.0688 - val_class_weights_1_loss: 0.0431 - val_class_weights_2_loss: 0.0876 - val_class_weights_3_loss: 0.0809 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9550 - val_class_weights_2_accuracy: 0.8800 - val_class_weights_3_accuracy: 0.9050



Epoch 00006: val_loss did not improve from 0.24997
Epoch 7/10
25/25 [==============================] - 27201s 1088s/step - loss: 0.2243 - class_weights_loss: 0.0505 - class_weights_1_loss: 0.0359 - class_weights_2_loss: 0.0913 - class_weights_3_loss: 0.0467 - class_weights_accuracy: 0.9440 - class_weights_1_accuracy: 0.9673 - class_weights_2_accuracy: 0.8894 - class_weights_3_accuracy: 0.9528 - val_loss: 0.2523 - val_class_weights_loss: 0.0630 - val_class_weights_1_loss: 0.0314 - val_class_weights_2_loss: 0.0976 - val_class_weights_3_loss: 0.0603 - val_class_weights_accuracy: 0.9350 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8700 - val_class_weights_3_accuracy: 0.9300



Epoch 00007: val_loss did not improve from 0.24997
Epoch 8/10
25/25 [==============================] - 26846s 1076s/step - loss: 0.1959 - class_weights_loss: 0.0435 - class_weights_1_loss: 0.0231 - class_weights_2_loss: 0.0802 - class_weights_3_loss: 0.0490 - class_weights_accuracy: 0.9612 - class_weights_1_accuracy: 0.9790 - class_weights_2_accuracy: 0.8961 - class_weights_3_accuracy: 0.9490 - val_loss: 0.2641 - val_class_weights_loss: 0.0573 - val_class_weights_1_loss: 0.0355 - val_class_weights_2_loss: 0.1009 - val_class_weights_3_loss: 0.0703 - val_class_weights_accuracy: 0.9550 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8550 - val_class_weights_3_accuracy: 0.9150



Epoch 00008: val_loss did not improve from 0.24997
Epoch 9/10
25/25 [==============================] - 27045s 1083s/step - loss: 0.1974 - class_weights_loss: 0.0409 - class_weights_1_loss: 0.0314 - class_weights_2_loss: 0.0815 - class_weights_3_loss: 0.0436 - class_weights_accuracy: 0.9536 - class_weights_1_accuracy: 0.9821 - class_weights_2_accuracy: 0.8896 - class_weights_3_accuracy: 0.9465 - val_loss: 0.2531 - val_class_weights_loss: 0.0580 - val_class_weights_1_loss: 0.0449 - val_class_weights_2_loss: 0.0933 - val_class_weights_3_loss: 0.0569 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.8750 - val_class_weights_3_accuracy: 0.9150



Epoch 00009: val_loss did not improve from 0.24997
Epoch 10/10
25/25 [==============================] - 26934s 1078s/step - loss: 0.1975 - class_weights_loss: 0.0504 - class_weights_1_loss: 0.0277 - class_weights_2_loss: 0.0795 - class_weights_3_loss: 0.0398 - class_weights_accuracy: 0.9526 - class_weights_1_accuracy: 0.9679 - class_weights_2_accuracy: 0.9014 - class_weights_3_accuracy: 0.9570 - val_loss: 0.2513 - val_class_weights_loss: 0.0637 - val_class_weights_1_loss: 0.0314 - val_class_weights_2_loss: 0.0936 - val_class_weights_3_loss: 0.0627 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9650 - val_class_weights_2_accuracy: 0.8700 - val_class_weights_3_accuracy: 0.9250



Epoch 00010: val_loss did not improve from 0.24997


In [110]:
# model weights with best val loss
model.load_weights('./Model/4_QConv2ent_2QFC_valloss.hdf5')
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-3.5068619e-01, -7.3729032e-01,  4.9220048e-02, -1.3541983e+00,
           6.9659483e-01,  2.0142789e+00, -1.1912005e-01,  4.4253272e-01,
           8.0796504e-01],
         [ 2.8853995e-01,  2.5525689e-03, -7.5066173e-01, -5.1612389e-01,
          -7.6931775e-01,  3.9495945e-02, -2.9847270e-01, -2.9303998e-01,
           5.8868647e-01]],
 
        [[ 1.7989293e+00,  2.7588477e+00,  1.4450849e+00, -1.1718978e+00,
          -2.5184264e-02,  1.3628511e+00, -7.9603838e-03, -4.2075574e-01,
           5.2138257e-01],
         [ 1.3797082e+00, -1.3904944e-01, -3.8255316e-01, -8.2376450e-02,
          -1.5615442e-01,  3.5362953e-01,  2.2989626e-01,  2.2489822e-01,
           5.5747521e-01]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.8364928 , -2.4098628 , -1.5612396 , -1.9017003 ,
           1.9548664 , -0.

In [108]:
# next 10 epochs after lr decay
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-3.6644542e-01, -6.6770083e-01,  1.3986501e-01, -1.1418517e+00,
           3.0379483e-01,  2.3430648e+00, -2.3379631e-01,  1.4587849e-01,
           7.7585179e-01],
         [ 1.9207229e-01,  2.5525689e-03, -7.5683773e-01, -5.1612389e-01,
          -5.1005733e-01,  3.9495945e-02, -5.8506036e-01, -2.9303998e-01,
           5.6093866e-01]],
 
        [[ 1.7280260e+00,  2.6054318e+00,  1.6298077e+00, -1.3270444e+00,
           1.2432319e-01,  1.4316064e+00,  2.5483015e-01, -3.5418484e-01,
           6.6999710e-01],
         [ 1.6354799e+00, -1.3904944e-01, -1.9403182e-01, -8.2376450e-02,
          -1.4878730e-01,  3.5362953e-01,  4.3237948e-01,  2.2489822e-01,
           6.8945587e-01]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.9933352 , -2.4469004 , -1.6512814 , -1.877328  ,
           1.9617206 , -0.

In [37]:
# next 10 epochs after lr decay
H.history

{'loss': [0.3103928864002228,
  0.2459564059972763,
  0.24032063782215118,
  0.22021402418613434,
  0.23440174758434296,
  0.23070552945137024,
  0.23007187247276306,
  0.21205854415893555,
  0.20605629682540894,
  0.1999938040971756],
 'class_weights_loss': [0.06540413945913315,
  0.05067485198378563,
  0.05085073038935661,
  0.04367179051041603,
  0.04891195893287659,
  0.04916946589946747,
  0.05484521761536598,
  0.04836016520857811,
  0.045355964452028275,
  0.04693691432476044],
 'class_weights_1_loss': [0.050603460520505905,
  0.033431313931941986,
  0.03725619241595268,
  0.036528609693050385,
  0.0380219966173172,
  0.0354028083384037,
  0.03314359486103058,
  0.02903129532933235,
  0.029368706047534943,
  0.028842007741332054],
 'class_weights_2_loss': [0.1129121333360672,
  0.10480396449565887,
  0.095039501786232,
  0.09446433931589127,
  0.0997384712100029,
  0.0947929322719574,
  0.09103287011384964,
  0.08576420694589615,
  0.08413051813840866,
  0.0804881602525711],
 'c

In [31]:
# first 10 epochs before lr decay
H.history

{'loss': [1.0111608505249023,
  0.6868469715118408,
  0.5057929158210754,
  0.44260281324386597,
  0.35056832432746887,
  0.2968459129333496,
  0.2924039363861084,
  0.2602747976779938,
  0.26590603590011597,
  0.2575048506259918],
 'class_weights_loss': [0.26925164461135864,
  0.15809020400047302,
  0.08490398526191711,
  0.0776936411857605,
  0.06354520469903946,
  0.05990614369511604,
  0.05566360056400299,
  0.056557122617959976,
  0.0627477765083313,
  0.057271718978881836],
 'class_weights_1_loss': [0.24753987789154053,
  0.1477098912000656,
  0.08074972778558731,
  0.07177780568599701,
  0.046477146446704865,
  0.04214911535382271,
  0.05117877572774887,
  0.04142901301383972,
  0.03364543616771698,
  0.04256885126233101],
 'class_weights_2_loss': [0.2458696812391281,
  0.18835708498954773,
  0.16963106393814087,
  0.15835900604724884,
  0.12704524397850037,
  0.11556874215602875,
  0.10782639682292938,
  0.10440581291913986,
  0.102692611515522,
  0.09769731760025024],
 'class_

In [32]:
# first 10 epochs before lr decay
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.204333  , -0.9065615 ,  0.40738553, -1.1753407 ,
           0.9621245 ,  2.018857  , -0.3183474 ,  0.26782325,
           0.72603637],
         [ 0.10142553,  0.00255257, -0.7550016 , -0.5161239 ,
          -0.7630532 ,  0.03949594, -0.3264697 , -0.29303998,
           0.5397937 ]],
 
        [[ 1.7459589 ,  2.444865  ,  1.7272474 , -1.0620315 ,
           0.0189265 ,  1.1139463 , -0.20810643, -0.2684929 ,
           0.32006234],
         [ 1.3082465 , -0.13904944, -0.5299284 , -0.08237645,
          -0.13254017,  0.35362953,  0.39849976,  0.22489822,
           0.40491554]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.6681657 , -2.0086706 , -1.4954917 , -1.7829584 ,
           1.8330503 , -0.31931466, -3.97961   ,  0.24756432,
           0.36602587],
         [ 0.998142  ,  0.4393435 , -0.7992056 ,

# Result Analysis

In [232]:
# model weights with best val loss
model.load_weights('./Model/4_QConv2ent_2QFC_valloss.hdf5')
model.weights

[<tf.Variable 'model_5/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-3.5068619e-01, -7.3729032e-01,  4.9220048e-02, -1.3541983e+00,
           6.9659483e-01,  2.0142789e+00, -1.1912005e-01,  4.4253272e-01,
           8.0796504e-01],
         [ 2.8853995e-01,  2.5525689e-03, -7.5066173e-01, -5.1612389e-01,
          -7.6931775e-01,  3.9495945e-02, -2.9847270e-01, -2.9303998e-01,
           5.8868647e-01]],
 
        [[ 1.7989293e+00,  2.7588477e+00,  1.4450849e+00, -1.1718978e+00,
          -2.5184264e-02,  1.3628511e+00, -7.9603838e-03, -4.2075574e-01,
           5.2138257e-01],
         [ 1.3797082e+00, -1.3904944e-01, -3.8255316e-01, -8.2376450e-02,
          -1.5615442e-01,  3.5362953e-01,  2.2989626e-01,  2.2489822e-01,
           5.5747521e-01]]], dtype=float32)>,
 <tf.Variable 'model_5/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.8364928 , -2.4098628 , -1.5612396 , -1.9017003 ,
           1.9548664 ,

In [236]:
test_res = model.predict(X_test)

In [237]:
train_res = model.predict(X_train)

In [238]:
test_res[0][0]

array([0.9478839, 0.0716159], dtype=float32)

In [239]:
train_res[0].shape

(800, 2)

In [240]:
def ave_loss(class_pred):
    return ((class_pred[0] - 1)**2 + (class_pred[1] - 0)**2)

In [241]:
train_pred = np.zeros((len(train_res[0]), ))

# samples loop
for i in range(len(train_res[0])):
    temp_max = 0
    class_max = None
    
    # class loop
    for j in range(4):
        # check positive class
        if temp_max < train_res[j][i][0]:
            temp_max = train_res[j][i][0]
            class_max = j
            
    train_pred[i] = class_max

In [242]:
((Y_train == train_pred).sum())/(len(train_pred))

tensor(0.8975, requires_grad=True)

In [250]:
train_pred = np.zeros((len(train_res[0]), ))

# samples loop
for i in range(len(train_res[0])):
    temp_min = 100
    class_min = None
    
    # class loop
    for j in range(4):
        # check loss value
        if temp_min > ave_loss(train_res[j][i]):
            temp_min = ave_loss(train_res[j][i])
            class_min = j
            
    train_pred[i] = class_min

In [251]:
((Y_train == train_pred).sum())/(len(train_pred))

tensor(0.9, requires_grad=True)

In [256]:
# best val loss weights
# lowest mse
# wrong train sample

np.where((Y_train == train_pred) == False)[0]

array([  2,  24,  26,  75,  91,  97, 112, 114, 150, 180, 194, 205, 221,
       231, 261, 303, 327, 348, 353, 359, 388, 406, 410, 414, 417, 425,
       430, 440, 441, 443, 457, 460, 462, 466, 471, 474, 478, 481, 487,
       489, 494, 495, 504, 508, 511, 516, 519, 521, 522, 525, 527, 530,
       531, 533, 552, 553, 555, 569, 579, 583, 586, 587, 595, 596, 640,
       647, 650, 652, 664, 702, 711, 717, 723, 726, 727, 729, 765, 780,
       783, 784])

In [178]:
# method of determining true class


# weights after 10 epochs lr decay
# highest positive value: train 0.90125, test 0.83
# lowest mse: train 0.90375, test 0.83


# best val loss weights
# highest positive value: train 0.8975, test 0.865
# lowest mse: train 0.9, test 0.865

In [246]:
test_pred = np.zeros((len(test_res[0]), ))

# samples loop
for i in range(len(test_res[0])):
    temp_max = 0
    class_max = None
    
    # class loop
    for j in range(4):
        # check positive class
        if temp_max < test_res[j][i][0]:
            temp_max = test_res[j][i][0]
            class_max = j
            
    test_pred[i] = class_max

In [247]:
((Y_test == test_pred).sum())/(len(test_pred))

tensor(0.865, requires_grad=True)

In [259]:
test_pred = np.zeros((len(test_res[0]), ))

# samples loop
for i in range(len(test_res[0])):
    temp_min = 100
    class_min = None
    
    # class loop
    for j in range(4):
        # check loss value
        if temp_min > ave_loss(test_res[j][i]):
            temp_min = ave_loss(test_res[j][i])
            class_min = j
            
    test_pred[i] = class_min

In [260]:
((Y_test == test_pred).sum())/(len(test_pred))

tensor(0.865, requires_grad=True)

In [264]:
# best val loss weights
# lowest mse
# wrong test sample

np.where((Y_test == test_pred) == False)[0]

array([  5,  10,  12,  27,  29,  30,  31,  36,  37,  38,  41,  43,  47,
        48,  63,  76, 103, 111, 118, 122, 136, 139, 162, 177, 181, 186,
       193])

# Exploring the results

In [122]:
# model weights with best val loss
model.load_weights('./Model/4_QConv2ent_2QFC_valloss.hdf5')
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-3.5068619e-01, -7.3729032e-01,  4.9220048e-02, -1.3541983e+00,
           6.9659483e-01,  2.0142789e+00, -1.1912005e-01,  4.4253272e-01,
           8.0796504e-01],
         [ 2.8853995e-01,  2.5525689e-03, -7.5066173e-01, -5.1612389e-01,
          -7.6931775e-01,  3.9495945e-02, -2.9847270e-01, -2.9303998e-01,
           5.8868647e-01]],
 
        [[ 1.7989293e+00,  2.7588477e+00,  1.4450849e+00, -1.1718978e+00,
          -2.5184264e-02,  1.3628511e+00, -7.9603838e-03, -4.2075574e-01,
           5.2138257e-01],
         [ 1.3797082e+00, -1.3904944e-01, -3.8255316e-01, -8.2376450e-02,
          -1.5615442e-01,  3.5362953e-01,  2.2989626e-01,  2.2489822e-01,
           5.5747521e-01]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.8364928 , -2.4098628 , -1.5612396 , -1.9017003 ,
           1.9548664 , -0.

## First Layer

In [123]:
qconv_1_weights = np.array([[[-3.5068619e-01, -7.3729032e-01,  4.9220048e-02, -1.3541983e+00,
           6.9659483e-01,  2.0142789e+00, -1.1912005e-01,  4.4253272e-01,
           8.0796504e-01],
         [ 2.8853995e-01,  2.5525689e-03, -7.5066173e-01, -5.1612389e-01,
          -7.6931775e-01,  3.9495945e-02, -2.9847270e-01, -2.9303998e-01,
           5.8868647e-01]],
 
        [[ 1.7989293e+00,  2.7588477e+00,  1.4450849e+00, -1.1718978e+00,
          -2.5184264e-02,  1.3628511e+00, -7.9603838e-03, -4.2075574e-01,
           5.2138257e-01],
         [ 1.3797082e+00, -1.3904944e-01, -3.8255316e-01, -8.2376450e-02,
          -1.5615442e-01,  3.5362953e-01,  2.2989626e-01,  2.2489822e-01,
           5.5747521e-01]]])

qconv_1_weights.shape

(2, 2, 9)

In [124]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)

qconv1_model = tf.keras.Model(inputs=X, outputs=reshape_layer_1)


In [125]:
qconv1_model(X_train[0:1])
qconv1_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])

In [132]:
np.isclose(qconv1_model.get_weights()[0], qconv_1_weights).sum()

tensor(36, requires_grad=True)

In [134]:
preprocessed_img_train = qconv1_model(X_train)

preprocessed_img_test = qconv1_model(X_test)

data_train = preprocessed_img_train.numpy().reshape(-1, 13*13)
np.savetxt('./4_QConv2ent_QFC2_Branch-Filter1_Image_Train.txt', data_train)

data_test = preprocessed_img_test.numpy().reshape(-1, 13*13)
np.savetxt('./4_QConv2ent_QFC2_Branch-Filter1_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(800, 169) (200, 169)


## Second Layer

In [135]:
qconv_2_weights = np.array([[[ 2.8364928 , -2.4098628 , -1.5612396 , -1.9017003 ,
           1.9548664 , -0.37646097, -4.222284  ,  0.26775557,
           0.18441878],
         [ 0.7034124 ,  0.4393435 , -0.32212317, -0.17706996,
           0.2777927 , -0.40236515, -0.33229282,  0.35953867,
          -1.9918324 ]],
 
        [[-1.6619883 ,  0.33638576,  0.49042726,  0.6765302 ,
           0.22028887, -0.72008365,  2.4235497 ,  0.13619412,
          -0.69446284],
         [-0.54379666,  0.40716565,  0.07379556, -0.01504666,
           0.5636293 ,  0.11656392, -0.08756571,  0.3454725 ,
           0.37661582]]])

qconv_2_weights.shape

(2, 2, 9)

In [136]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)

qconv2_model = tf.keras.Model(inputs=X, outputs=reshape_layer_2)


In [137]:
qconv2_model(X_train[0:1])
qconv2_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])
qconv2_model.get_layer('Quantum_Conv_Layer_2').set_weights([qconv_2_weights])

In [140]:
np.isclose(qconv2_model.get_weights()[0], qconv_1_weights).sum()

tensor(36, requires_grad=True)

In [141]:
np.isclose(qconv2_model.get_weights()[1], qconv_2_weights).sum()

tensor(36, requires_grad=True)

In [142]:
preprocessed_img_train = qconv2_model(X_train)

preprocessed_img_test = qconv2_model(X_test)

data_train = preprocessed_img_train.numpy().reshape(-1, 6*6)
np.savetxt('./4_QConv2ent_QFC2_Branch-Filter2_Image_Train.txt', data_train)

data_test = preprocessed_img_test.numpy().reshape(-1, 6*6)
np.savetxt('./4_QConv2ent_QFC2_Branch-Filter2_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(800, 36) (200, 36)


## Quantum States

In [143]:
q_fc_weights_0 = np.array([[[ 0.34919307,  1.280577  , -0.40389746,  2.7567825 ,
          -1.8981032 , -0.58490497, -2.6140049 ,  0.55854434,
          -0.14549442],
         [ 1.8742485 ,  1.3923526 , -0.48553988, -4.0282655 ,
          -1.0092568 , -1.726109  ,  0.28595045,  0.35788605,
           0.13558954]],
 
        [[-0.06619656,  0.29138508,  0.34191862,  0.7155059 ,
          -0.20389102, -1.6070857 , -1.5218158 ,  1.034849  ,
          -0.06948825],
         [-0.16024663,  0.61659706,  0.14865518, -0.59474736,
           1.3341626 , -0.05620752,  0.3439594 , -0.09109917,
          -0.01229791]]])

q_fc_weights_1 = np.array([[[ 0.28862742,  0.8386173 , -1.0520895 , -0.76006484,
           1.6054868 , -0.8180273 , -1.3015922 ,  0.146214  ,
          -2.9870028 ],
         [-1.1344436 , -1.3247255 ,  0.58105224,  0.66553676,
           2.252441  , -0.13002443, -1.3606563 ,  0.9464437 ,
          -0.31959775]],
 
        [[ 0.20303592,  0.5243242 , -0.9218817 , -1.370076  ,
           0.7210135 , -0.6125907 , -0.33028948,  0.49510303,
          -0.53149074],
         [-0.5199091 , -1.8823092 , -0.45752335, -0.5516297 ,
          -1.2591928 , -0.37027845, -0.88656336, -0.14877637,
           0.04090607]]])

q_fc_weights_2 = np.array([[[ 0.32965487, -0.48179072,  0.59025586, -3.1451197 ,
           2.5917895 , -0.71461445, -1.5514388 , -1.2567754 ,
           0.03566303],
         [-2.6445682 ,  0.18470715,  0.8170568 , -1.2547797 ,
           1.6798987 , -0.895823  , -2.0204744 ,  2.1893585 ,
           0.38608813]],
 
        [[-0.46725035, -0.88657665,  0.08115988, -0.33190268,
           0.3567504 , -0.06429264,  0.4678363 ,  1.11554   ,
          -0.7310539 ],
         [-0.2545552 ,  0.45082113, -0.31482646, -0.3524591 ,
           0.19939618, -0.83299035, -1.3128988 , -0.33097702,
           0.36383504]]])

q_fc_weights_3 = np.array([[[ 0.43416622, -0.5376355 , -0.48654264,  4.231484  ,
          -0.8790685 ,  1.179932  , -1.6252736 , -2.3226252 ,
           2.8246262 ],
         [ 0.46730754,  0.44019   ,  0.5064762 , -2.5414548 ,
           0.8346419 ,  0.67727995, -1.7355382 ,  3.571513  ,
          -0.22530685]],
 
        [[-0.21687755, -0.71872264,  1.7950757 ,  1.1021243 ,
          -1.156439  ,  0.4487198 ,  0.40195227, -0.9239927 ,
           0.26137996],
         [ 0.30011192, -1.3315674 , -0.7748441 , -1.0567622 ,
          -0.95007855, -2.145618  , -1.6848673 , -0.6859795 ,
          -0.507362  ]]])


q_fc_weights_0.shape, q_fc_weights_1.shape, q_fc_weights_2.shape, q_fc_weights_3.shape

((2, 2, 9), (2, 2, 9), (2, 2, 9), (2, 2, 9))

In [144]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)

maxpool_model = tf.keras.Model(inputs=X, outputs=reshape_layer_3)


In [145]:
maxpool_model(X_train[0:1])
maxpool_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])
maxpool_model.get_layer('Quantum_Conv_Layer_2').set_weights([qconv_2_weights])

In [146]:
maxpool_train = maxpool_model(X_train)
maxpool_test = maxpool_model(X_test)

maxpool_train.shape, maxpool_test.shape

(TensorShape([800, 9]), TensorShape([200, 9]))

In [266]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [267]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [150]:
# branch 0

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_0, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_0, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [153]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
 False  True False  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True False
  True  True  True False  True  True  True  True  True  True  True  True
 False  True  True  True  True False  True False False  True  True  True
  True False  True  True  True False  True False  True  True  True  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [154]:
np.savetxt('./4_0_QConv2ent_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_0_QConv2ent_QFC2_Branch-State_Test.txt', test_state)

In [155]:
# branch 1

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_1, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_1, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [156]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [157]:
np.savetxt('./4_1_QConv2ent_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_1_QConv2ent_QFC2_Branch-State_Test.txt', test_state)

In [158]:
# branch 2

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_2, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_2, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [159]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False False
 False  True False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False Fa

In [160]:
np.savetxt('./4_2_QConv2ent_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_2_QConv2ent_QFC2_Branch-State_Test.txt', test_state)

In [268]:
# branch 3

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights_3, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(q_fc_weights_3, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [269]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True  True False False False False False
 False False False False False False False False Fa

In [163]:
np.savetxt('./4_3_QConv2ent_QFC2_Branch-State_Train.txt', train_state)
np.savetxt('./4_3_QConv2ent_QFC2_Branch-State_Test.txt', test_state)

## Saving trained max pool output

In [272]:
maxpool_train.shape, maxpool_test.shape

(TensorShape([800, 9]), TensorShape([200, 9]))

In [273]:
np.savetxt('./4_QConv2ent_QFC2_Branch-TrainedMaxPool_Train.txt', maxpool_train)
np.savetxt('./4_QConv2ent_QFC2_Branch-TrainedMaxPool_Test.txt', maxpool_test)

## Random Starting State

In [274]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)



model_random = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])
model_maxpool_random = tf.keras.Model(inputs=X, outputs=reshape_layer_3)

In [275]:
model_random(X_train[0:1])
model_random.weights

[<tf.Variable 'model_6/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.4935665 , -0.42099395, -0.2597131 ,  0.2966947 ,
          -0.10505533,  0.28274912, -0.03773376,  0.11435151,
          -0.35377386],
         [ 0.22746724, -0.3884052 , -0.2771201 , -0.330773  ,
          -0.34085816,  0.0066303 , -0.05477595, -0.4197226 ,
           0.27047753]],
 
        [[ 0.04934853,  0.03703487, -0.30145934,  0.43903697,
          -0.32865083,  0.3199892 ,  0.12504756,  0.39701498,
          -0.00629622],
         [-0.1274552 ,  0.2433902 , -0.4604111 , -0.40842503,
           0.17800081,  0.17491269, -0.22741085,  0.07822168,
          -0.48920503]]], dtype=float32)>,
 <tf.Variable 'model_6/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.0467214 , -0.25141215,  0.4850946 ,  0.02253991,
           0.36952686, -0.52052516,  0.3910737 , -0.02388251,
           0.5033249 ],
         [-0.26109344, -0.38241404,  0.07779

In [276]:
random_weights_0 = np.array([[[-0.38205916, -0.32157356, -0.36946476, -0.14519015,
          -0.1741243 , -0.14436567,  0.41515827,  0.46430767,
           0.05232906],
         [ 0.45858866, -0.27274096,  0.09459215,  0.1331594 ,
           0.26793003,  0.35317045, -0.25254235,  0.35575753,
          -0.00269699]],
 
        [[ 0.20839894, -0.06481433, -0.389221  ,  0.18636137,
           0.0322125 , -0.4043268 , -0.23117393,  0.2731933 ,
          -0.33924854],
         [ 0.00189614,  0.47282887, -0.47041848, -0.2506976 ,
           0.23154783,  0.5169259 , -0.38120353, -0.29712826,
          -0.3661686 ]]])

random_weights_1 = np.array([[[-3.8573855e-01,  1.2338161e-04, -3.4994566e-01,  1.6507030e-02,
           2.7931094e-02,  1.4965594e-01,  1.9558185e-01,  3.7240016e-01,
           4.1224837e-01],
         [-2.0730710e-01,  1.4665091e-01,  2.2953910e-01, -1.8294707e-01,
          -2.9422033e-01, -1.0954219e-01, -4.8812094e-01,  2.3804653e-01,
           1.2762904e-02]],
 
        [[-3.7277770e-01,  4.7162807e-01,  1.7469132e-01,  1.9624650e-01,
           6.5971136e-02, -3.0559468e-01,  5.2143711e-01,  2.9053259e-01,
          -3.3940887e-01],
         [ 7.6271355e-02,  2.2447646e-02, -1.9267979e-01, -3.3340788e-01,
           3.0921632e-01, -8.3895922e-03, -4.2881757e-02, -1.0280296e-01,
           1.6796750e-01]]])

random_weights_2 = np.array([[[ 0.3375085 , -0.5039589 , -0.12458649,  0.03081298,
          -0.3590887 ,  0.10382867,  0.40024424, -0.36897716,
           0.31312758],
         [ 0.42523754, -0.03742361,  0.06040829, -0.06957746,
           0.30570823, -0.11539704, -0.40476683, -0.23915961,
          -0.0829832 ]],
 
        [[ 0.3559941 ,  0.3155442 ,  0.08222359,  0.41432273,
           0.01732248, -0.26297218, -0.01981091, -0.04592776,
           0.39101595],
         [ 0.3062536 , -0.08849475, -0.20818016, -0.44495705,
           0.06605953, -0.13090187, -0.3172878 , -0.5133143 ,
          -0.4394003 ]]])

random_weights_3 = np.array([[[ 0.21720552, -0.46527594, -0.01723516,  0.32298315,
          -0.17747   , -0.26591384, -0.43713358,  0.08005935,
          -0.44423178],
         [-0.37649596,  0.41977262,  0.15621603, -0.3686198 ,
           0.34089315, -0.07570398,  0.30436516, -0.04764476,
          -0.3341527 ]],
 
        [[-0.19360352,  0.0107705 ,  0.05996364, -0.30747455,
           0.3622191 ,  0.27814162, -0.01553947,  0.0343135 ,
           0.09682399],
         [-0.37713268, -0.2690144 , -0.34324157, -0.16356263,
           0.24849337, -0.23426789, -0.02752119,  0.22051013,
          -0.14259636]]])

In [277]:
maxpool_train = model_maxpool_random(X_train)
maxpool_test = model_maxpool_random(X_test)

maxpool_train.shape, maxpool_test.shape

(TensorShape([800, 9]), TensorShape([200, 9]))

In [278]:
np.savetxt('./4_QConv2ent_QFC2_Branch-RandomMaxPool_Train.txt', maxpool_train)
np.savetxt('./4_QConv2ent_QFC2_Branch-RandomMaxPool_Test.txt', maxpool_test)

In [279]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [280]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [281]:
# branch 0

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_0, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_0, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [282]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [283]:
np.savetxt('./4_0_QConv2ent_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_0_QConv2ent_QFC2_Branch-RandomState_Test.txt', test_state)

In [284]:
# branch 1

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_1, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_1, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [285]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [286]:
np.savetxt('./4_1_QConv2ent_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_1_QConv2ent_QFC2_Branch-RandomState_Test.txt', test_state)

In [287]:
# branch 2

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_2, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_2, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [288]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [289]:
np.savetxt('./4_2_QConv2ent_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_2_QConv2ent_QFC2_Branch-RandomState_Test.txt', test_state)

In [290]:
# branch 3

train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights_3, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
for i in range(len(test_state)):
    
    q_fc_state(random_weights_3, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp
    
train_state.shape, test_state.shape

((800, 2), (200, 2))

In [291]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  T

In [292]:
np.savetxt('./4_3_QConv2ent_QFC2_Branch-RandomState_Train.txt', train_state)
np.savetxt('./4_3_QConv2ent_QFC2_Branch-RandomState_Test.txt', test_state)