In [23]:
# Mount Google Drive
from google.colab import drive # import drive from google colab
 
ROOT = "/content/drive"     # default location for the drive
print(ROOT)                 # print content of ROOT (Optional)
 
drive.mount(ROOT)           # we mount the google drive at /content/drive

/content/drive
Mounted at /content/drive


In [33]:
%cd "/content/drive/My Drive/Projects/quantum_image_classifier/PennyLane/Data Reuploading Classifier"

/content/drive/My Drive/Projects/quantum_image_classifier/PennyLane/Data Reuploading Classifier


In [1]:
!pip install pennylane
from IPython.display import clear_output
clear_output()

In [ ]:
import os

def restart_runtime():
  os.kill(os.getpid(), 9)
restart_runtime()

In [1]:
# %matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

# Loading Raw Data

In [2]:
import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train[:, 0:27, 0:27]
x_test = x_test[:, 0:27, 0:27]

In [3]:
x_train_flatten = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])/255.0
x_test_flatten = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])/255.0

In [4]:
print(x_train_flatten.shape, y_train.shape)
print(x_test_flatten.shape, y_test.shape)

(60000, 729) (60000,)
(10000, 729) (10000,)


In [5]:
x_train_0 = x_train_flatten[y_train == 0]
x_train_1 = x_train_flatten[y_train == 1]
x_train_2 = x_train_flatten[y_train == 2]
x_train_3 = x_train_flatten[y_train == 3]
x_train_4 = x_train_flatten[y_train == 4]
x_train_5 = x_train_flatten[y_train == 5]
x_train_6 = x_train_flatten[y_train == 6]
x_train_7 = x_train_flatten[y_train == 7]
x_train_8 = x_train_flatten[y_train == 8]
x_train_9 = x_train_flatten[y_train == 9]

x_train_list = [x_train_0, x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6, x_train_7, x_train_8, x_train_9]

print(x_train_0.shape)
print(x_train_1.shape)
print(x_train_2.shape)
print(x_train_3.shape)
print(x_train_4.shape)
print(x_train_5.shape)
print(x_train_6.shape)
print(x_train_7.shape)
print(x_train_8.shape)
print(x_train_9.shape)

(5923, 729)
(6742, 729)
(5958, 729)
(6131, 729)
(5842, 729)
(5421, 729)
(5918, 729)
(6265, 729)
(5851, 729)
(5949, 729)


In [6]:
x_test_0 = x_test_flatten[y_test == 0]
x_test_1 = x_test_flatten[y_test == 1]
x_test_2 = x_test_flatten[y_test == 2]
x_test_3 = x_test_flatten[y_test == 3]
x_test_4 = x_test_flatten[y_test == 4]
x_test_5 = x_test_flatten[y_test == 5]
x_test_6 = x_test_flatten[y_test == 6]
x_test_7 = x_test_flatten[y_test == 7]
x_test_8 = x_test_flatten[y_test == 8]
x_test_9 = x_test_flatten[y_test == 9]

x_test_list = [x_test_0, x_test_1, x_test_2, x_test_3, x_test_4, x_test_5, x_test_6, x_test_7, x_test_8, x_test_9]

print(x_test_0.shape)
print(x_test_1.shape)
print(x_test_2.shape)
print(x_test_3.shape)
print(x_test_4.shape)
print(x_test_5.shape)
print(x_test_6.shape)
print(x_test_7.shape)
print(x_test_8.shape)
print(x_test_9.shape)

(980, 729)
(1135, 729)
(1032, 729)
(1010, 729)
(982, 729)
(892, 729)
(958, 729)
(1028, 729)
(974, 729)
(1009, 729)


# Selecting the dataset

Output: X_train, Y_train, X_test, Y_test

In [8]:
num_sample = 200
n_class = 4
mult_test = 0.25

X_train = x_train_list[0][:num_sample, :]
X_test = x_test_list[0][:int(mult_test*num_sample), :]

Y_train = np.zeros((n_class*X_train.shape[0],), dtype=int)
Y_test = np.zeros((n_class*X_test.shape[0],), dtype=int)

for i in range(n_class-1):
  X_train = np.concatenate((X_train, x_train_list[i+1][:num_sample, :]), axis=0)
  Y_train[num_sample*(i+1):num_sample*(i+2)] = int(i+1)

  X_test = np.concatenate((X_test, x_test_list[i+1][:int(mult_test*num_sample), :]), axis=0)
  Y_test[int(mult_test*num_sample*(i+1)):int(mult_test*num_sample*(i+2))] = int(i+1)

print(X_train.shape, Y_train.shape)
print(X_test.shape, Y_test.shape)

(800, 729) (800,)
(200, 729) (200,)


# Dataset Preprocessing

In [9]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((800, 27, 27), (200, 27, 27))

# Quantum

In [10]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer, GradientDescentOptimizer

qml.enable_tape()

from tensorflow.keras.utils import to_categorical

# Set a random seed
np.random.seed(2020)

In [11]:
# Define output labels as quantum state vectors

# def density_matrix(state):
#     """Calculates the density matrix representation of a state.

#     Args:
#         state (array[complex]): array representing a quantum state vector

#     Returns:
#         dm: (array[complex]): array representing the density matrix
#     """
#     return state * np.conj(state).T


label_0 = [[1], [0]]
label_1 = [[0], [1]]


def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return np.outer(state,  np.conj(state))

#state_labels = [label_0, label_1]
state_labels = np.loadtxt('./tetra_states.txt', dtype=np.complex_)

In [12]:
dm_labels = [density_matrix(state_labels[i]) for i in range(4)]
len(dm_labels)

4

In [13]:
dm_labels

[tensor([[1.+0.j, 0.+0.j],
         [0.+0.j, 0.+0.j]], requires_grad=True),
 tensor([[0.33333333+0.j, 0.47140452+0.j],
         [0.47140452+0.j, 0.66666667+0.j]], requires_grad=True),
 tensor([[ 0.33333333+0.j        , -0.23570226-0.40824829j],
         [-0.23570226+0.40824829j,  0.66666667+0.j        ]], requires_grad=True),
 tensor([[ 0.33333333+0.j        , -0.23570226+0.40824829j],
         [-0.23570226-0.40824829j,  0.66666667+0.j        ]], requires_grad=True)]

In [14]:
n_qubits = 4  # number of class
dev_fc = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs = [x, y]
        x (array[float]): 1-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(dm_labels[i], wires=[i])) for i in range(n_qubits)]


In [15]:
dev_conv = qml.device("default.qubit", wires=9)


@qml.qnode(dev_conv)
def q_conv(conv_params, inputs):
    """A variational quantum circuit representing the Universal classifier + Conv.

    Args:
        params (array[float]): array of parameters
        x (array[float]): 2-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    # layer iteration
    for l in range(len(conv_params[0])):
        # RY layer
        # height iteration
        for i in range(3):
            # width iteration
            for j in range(3):
                qml.RY((conv_params[0][l][3*i+j] * inputs[i, j] + conv_params[1][l][3*i+j]), wires=(3*i+j))

        # entangling layer
        for i in range(9):
            if i != (9-1):
                qml.CNOT(wires=[i, i+1])
                
    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2) @ qml.PauliZ(3) @ qml.PauliZ(4) @ qml.PauliZ(5) @ qml.PauliZ(6) @ qml.PauliZ(7) @ qml.PauliZ(8))

In [16]:
a = np.zeros((2, 1, 9))
q_conv(a, X_train[0, 0:3, 0:3])

tensor(1., requires_grad=True)

In [17]:
a = np.zeros((2, 1, 9))
q_fc(a, X_train[0, 0, 0:9])

tensor([1.        , 0.33333333, 0.33333333, 0.33333333], requires_grad=True)

In [18]:
tetra_class = np.loadtxt('./tetra_class_label.txt')
binary_class = np.array([[1, 0], [0, 1]])

square_class = np.array(np.loadtxt('./square_class_label.txt', dtype=np.complex_), dtype=float)

/home/ta-edo/.local/lib/python3.8/site-packages/autograd/numpy/numpy_wrapper.py:73: ComplexWarning: Casting complex values to real discards the imaginary part
  return _np.array(scalar, *array_args, **array_kwargs)


In [19]:
class_labels = tetra_class

In [20]:
class_labels

tensor([[1.        , 0.33333333, 0.33333333, 0.33333333],
        [0.33333333, 1.        , 0.33333333, 0.33333333],
        [0.33333333, 0.33333333, 1.        , 0.33333333],
        [0.33333333, 0.33333333, 0.33333333, 1.        ]], requires_grad=True)

In [21]:
n_class = 4

temp = np.zeros((len(Y_train), n_class))
for i in range(len(Y_train)):
    temp[i, :] = class_labels[Y_train[i]]
Y_train = temp


temp = np.zeros((len(Y_test), n_class))
for i in range(len(Y_test)):
    temp[i, :] = class_labels[Y_test[i]]
Y_test = temp

In [23]:
Y_test

tensor([[1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.        , 0.33333333, 0.33333333, 0.33333333],
        [1.   

In [24]:
from keras import backend as K


# Alpha Custom Layer
class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, n_class), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [31]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=n_class)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)

model = tf.keras.Model(inputs=X, outputs=alpha_layer_0)

In [32]:
model(X_train[0:32, :, :])

<tf.Tensor: shape=(32, 4), dtype=float32, numpy=
array([[-0.07996774,  0.08851518, -0.00153418, -0.00579961],
       [-0.07990675,  0.08857627, -0.001537  , -0.00576993],
       [-0.07988311,  0.08860483, -0.0015377 , -0.00576147],
       [-0.07979589,  0.08876715, -0.0015358 , -0.0057652 ],
       [-0.08001978,  0.08821127, -0.00155138, -0.00567427],
       [-0.07988558,  0.08855402, -0.00154137, -0.00573344],
       [-0.08002263,  0.08833262, -0.00154163, -0.00574921],
       [-0.08001868,  0.08835313, -0.00154053, -0.00575721],
       [-0.07998318,  0.08836707, -0.00154385, -0.00572704],
       [-0.08011331,  0.08812819, -0.00154625, -0.00572586],
       [-0.07998742,  0.0884057 , -0.00154031, -0.00575478],
       [-0.07978562,  0.08876869, -0.00153696, -0.00575495],
       [-0.07987887,  0.08863592, -0.00153579, -0.00577576],
       [-0.07970516,  0.0889352 , -0.00153384, -0.00576922],
       [-0.08002425,  0.08833872, -0.00154096, -0.00575463],
       [-0.07988572,  0.08870705, -0

In [33]:
import keras.backend as K

# def custom_loss(y_true, y_pred):
#     return K.sum(((y_true.shape[1]-2)*y_true+1)*K.square(y_true-y_pred))/len(y_true)

def custom_loss(y_true, y_pred):
    loss = K.square(y_true-y_pred)
    #class_weights = y_true*(weight_for_1-weight_for_0) + weight_for_0
    #loss = loss * class_weights
    
    return K.sum(loss)/len(y_true)

In [34]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
model.compile(opt, loss='mse', metrics=["accuracy"])

In [35]:
cp_val_acc = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_QFC_valacc.hdf5",
                monitor='val_accuracy', verbose=1, save_weights_only=True, save_best_only=True, mode='max')

cp_val_loss = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_QFC_valloss.hdf5",
                monitor='val_loss', verbose=1, save_weights_only=True, save_best_only=True, mode='min')

In [40]:
H = model.fit(X_train, Y_train, epochs=13, batch_size=32, initial_epoch=10,
              validation_data=(X_test, Y_test), verbose=1,
              callbacks=[cp_val_acc, cp_val_loss])

Epoch 11/13
25/25 [==============================] - 28124s 1127s/step - loss: 0.0474 - accuracy: 0.7000 - val_loss: 0.0522 - val_accuracy: 0.6600

Epoch 00011: val_accuracy did not improve from 0.70000

Epoch 00011: val_loss did not improve from 0.05203
Epoch 12/13
25/25 [==============================] - 27342s 1094s/step - loss: 0.0453 - accuracy: 0.7275 - val_loss: 0.0502 - val_accuracy: 0.7100

Epoch 00012: val_accuracy improved from 0.70000 to 0.71000, saving model to ./Model/4_QConv2ent_QFC_valacc.hdf5

Epoch 00012: val_loss improved from 0.05203 to 0.05020, saving model to ./Model/4_QConv2ent_QFC_valloss.hdf5
Epoch 13/13
25/25 [==============================] - 27667s 1109s/step - loss: 0.0460 - accuracy: 0.7450 - val_loss: 0.0529 - val_accuracy: 0.6650

Epoch 00013: val_accuracy did not improve from 0.71000

Epoch 00013: val_loss did not improve from 0.05020


In [37]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 27, 27)]     0                                            
__________________________________________________________________________________________________
tf.__operators__.getitem_205 (S (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_206 (S (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_207 (S (None, 3, 3)         0           Input_Layer[0][0]                
____________________________________________________________________________________________

In [38]:
# best first 10 epochs
H.history

{'loss': [0.17096687853336334,
  0.10371827334165573,
  0.08069191873073578,
  0.0615154467523098,
  0.05376540124416351,
  0.0523982048034668,
  0.0524703748524189,
  0.05090343952178955,
  0.04984511435031891,
  0.050022516399621964],
 'accuracy': [0.23749999701976776,
  0.26124998927116394,
  0.44999998807907104,
  0.6137499809265137,
  0.6462500095367432,
  0.6537500023841858,
  0.65625,
  0.6800000071525574,
  0.6837499737739563,
  0.7037500143051147],
 'val_loss': [0.11627619713544846,
  0.11223635822534561,
  0.08042151480913162,
  0.06282687187194824,
  0.059095434844493866,
  0.06476862728595734,
  0.0595523826777935,
  0.05885527282953262,
  0.05412958189845085,
  0.05203157290816307],
 'val_accuracy': [0.25,
  0.41999998688697815,
  0.5149999856948853,
  0.5899999737739563,
  0.6050000190734863,
  0.6200000047683716,
  0.6299999952316284,
  0.6600000262260437,
  0.699999988079071,
  0.6899999976158142]}

In [41]:
H.history

{'loss': [0.04735717922449112, 0.04525240510702133, 0.046018075197935104],
 'accuracy': [0.699999988079071, 0.7275000214576721, 0.7450000047683716],
 'val_loss': [0.05221995338797569, 0.05019545182585716, 0.05287088453769684],
 'val_accuracy': [0.6600000262260437, 0.7099999785423279, 0.6650000214576721]}

In [39]:
#best first 10 epochs
model.weights

[<tf.Variable 'model_1/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-2.9598436 ,  0.3716178 ,  0.48000816, -2.6687896 ,
           1.4801524 ,  0.38794804,  1.3911159 , -1.0252677 ,
          -1.0581573 ],
         [ 2.178519  ,  0.3181092 , -0.45470372, -0.46304935,
          -1.5537126 , -0.41695487, -0.03369746, -0.25906292,
          -1.101097  ]],
 
        [[ 0.46808168, -0.02797373, -0.01999639, -0.2689082 ,
          -2.0617254 ,  1.2333943 ,  1.6223339 ,  0.71393824,
          -0.96440226],
         [ 0.7278081 ,  0.23754972,  0.03524697, -0.21460065,
          -1.0412005 , -0.37866366,  1.0825651 , -0.25234276,
          -0.9527081 ]]], dtype=float32)>,
 <tf.Variable 'model_1/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 1.0146624 ,  2.2528083 ,  0.5254816 , -1.4097538 ,
           2.5723155 ,  3.1251209 , -1.8490754 ,  1.5022521 ,
          -1.1016043 ],
         [-2.7652028 ,  0.04445422, -1.59654

In [42]:
# best after 13 epochs
model.load_weights('./Model/4_QConv2ent_QFC_valacc.hdf5')
model.weights

[<tf.Variable 'model_1/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-2.9904091 ,  0.47873205,  0.51262283, -2.5594363 ,
           1.2622604 , -0.23898347,  1.2999494 , -0.7331065 ,
          -0.92392826],
         [ 2.0915756 ,  0.3181092 , -0.456017  , -0.46304935,
          -1.4806885 , -0.41695487,  0.03559908, -0.25906292,
          -1.595919  ]],
 
        [[ 0.03028841, -0.04068385,  0.01626368, -0.4585719 ,
          -2.2702715 ,  1.2751739 ,  1.4227612 ,  0.8768421 ,
          -1.0816092 ],
         [ 0.5383543 ,  0.23754972,  0.07477647, -0.21460065,
          -0.84343266, -0.37866366,  0.89809674, -0.25234276,
          -1.134891  ]]], dtype=float32)>,
 <tf.Variable 'model_1/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.87751925,  2.518178  ,  0.44218746, -1.2325302 ,
           2.7474535 ,  3.2063673 , -2.652964  ,  1.4717548 ,
          -1.399356  ],
         [-2.6943564 ,  0.04445422, -1.85744

# Exploring the results

In [26]:
X_train = np.concatenate((x_train_list[0][:20, :], x_train_list[1][:20, :]), axis=0)
Y_train = np.zeros((X_train.shape[0],), dtype=int)
Y_train[20:] += 1

X_train.shape, Y_train.shape

((40, 729), (40,))

In [27]:
X_test = np.concatenate((x_test_list[0][:20, :], x_test_list[1][:20, :]), axis=0)
Y_test = np.zeros((X_test.shape[0],), dtype=int)
Y_test[20:] += 1

X_test.shape, Y_test.shape

((40, 729), (40,))

In [28]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((40, 27, 27), (40, 27, 27))

## First Layer

In [29]:
qconv_1_weights = np.array([[[ 1.6704171 , -0.37210035, -1.4763509 , -0.09573141,
          -1.4124248 , -0.5384489 , -1.5873678 , -0.4178921 ,
           0.86764395]],
 
        [[ 0.07841697,  0.06181896, -0.11658821,  0.08088297,
          -0.22606611, -0.47507533,  0.20372277,  0.43287253,
          -0.4662246 ]]])

qconv_1_weights.shape

(2, 1, 9)

In [30]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 1
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)

qconv1_model = tf.keras.Model(inputs=X, outputs=reshape_layer_1)


In [31]:
qconv1_model(X_train[0:1])
qconv1_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])

In [32]:
qconv1_model.weights

[<tf.Variable 'model_1/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[ 1.6704171 , -0.37210035, -1.4763509 , -0.09573141,
          -1.4124248 , -0.5384489 , -1.5873678 , -0.4178921 ,
           0.86764395]],
 
        [[ 0.07841697,  0.06181896, -0.11658821,  0.08088297,
          -0.22606611, -0.47507533,  0.20372277,  0.43287253,
          -0.4662246 ]]], dtype=float32)>]

In [33]:
preprocessed_img_train = qconv1_model(X_train)

preprocessed_img_test = qconv1_model(X_test)

data_train = preprocessed_img_train.numpy().reshape(-1, 13*13)
np.savetxt('./2_QConv2ent_QFC-Filter1_Image_Train.txt', data_train)

data_test = preprocessed_img_test.numpy().reshape(-1, 13*13)
np.savetxt('./2_QConv2ent_QFC-Filter1_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(40, 169) (40, 169)


## Second Layer

In [34]:
qconv_2_weights = np.array([[[ 2.531285  , -0.53907233,  1.2279214 , -0.04873934,
          -1.9625113 , -0.31179625,  1.4537607 , -0.3272767 ,
           1.5368826 ]],
 
        [[ 0.8165296 ,  0.3640772 ,  1.7864715 ,  0.5245018 ,
          -1.6975542 , -0.21682522,  2.097541  ,  0.49968052,
           2.2059586 ]]])

qconv_2_weights.shape

(2, 1, 9)

In [35]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 1
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 1
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)

qconv2_model = tf.keras.Model(inputs=X, outputs=reshape_layer_2)


In [36]:
qconv2_model(X_train[0:1])
qconv2_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])
qconv2_model.get_layer('Quantum_Conv_Layer_2').set_weights([qconv_2_weights])

In [37]:
qconv2_model.weights

[<tf.Variable 'model_2/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[ 1.6704171 , -0.37210035, -1.4763509 , -0.09573141,
          -1.4124248 , -0.5384489 , -1.5873678 , -0.4178921 ,
           0.86764395]],
 
        [[ 0.07841697,  0.06181896, -0.11658821,  0.08088297,
          -0.22606611, -0.47507533,  0.20372277,  0.43287253,
          -0.4662246 ]]], dtype=float32)>,
 <tf.Variable 'model_2/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[ 2.531285  , -0.53907233,  1.2279214 , -0.04873934,
          -1.9625113 , -0.31179625,  1.4537607 , -0.3272767 ,
           1.5368826 ]],
 
        [[ 0.8165296 ,  0.3640772 ,  1.7864715 ,  0.5245018 ,
          -1.6975542 , -0.21682522,  2.097541  ,  0.49968052,
           2.2059586 ]]], dtype=float32)>]

In [38]:
preprocessed_img_train = qconv2_model(X_train)

preprocessed_img_test = qconv2_model(X_test)

data_train = preprocessed_img_train.numpy().reshape(-1, 6*6)
np.savetxt('./2_QConv2ent_QFC-Filter2_Image_Train.txt', data_train)

data_test = preprocessed_img_test.numpy().reshape(-1, 6*6)
np.savetxt('./2_QConv2ent_QFC-Filter2_Image_Test.txt', data_test)

print(data_train.shape, data_test.shape)

(40, 36) (40, 36)


## Quantum States

In [39]:
q_fc_weights = np.array([[[ 0.3726357 , -1.0686979 ,  0.24734715,  2.5706375 ,
           3.4816115 , -0.3167716 ,  1.2021828 ,  0.19082105,
           0.0209959 ]],
 
        [[-0.213224  ,  1.235254  ,  2.298314  ,  2.2815244 ,
          -1.1340573 ,  0.8286312 ,  0.6926544 , -1.0297745 ,
           0.14662777]]])

q_fc_weights.shape

(2, 1, 9)

In [40]:
pred_train = model.predict(X_train)
pred_test = model.predict(X_test)

In [41]:
np.argmax(pred_train, axis=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], requires_grad=True)

In [42]:
np.argmax(pred_test, axis=1)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], requires_grad=True)

In [43]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 1
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 1
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)

maxpool_model = tf.keras.Model(inputs=X, outputs=reshape_layer_3)


In [44]:
maxpool_model(X_train[0:1])
maxpool_model.get_layer('Quantum_Conv_Layer_1').set_weights([qconv_1_weights])
maxpool_model.get_layer('Quantum_Conv_Layer_2').set_weights([qconv_2_weights])

In [45]:
maxpool_train = maxpool_model(X_train)
maxpool_test = maxpool_model(X_test)

maxpool_train.shape, maxpool_test.shape

(TensorShape([40, 9]), TensorShape([40, 9]))

In [46]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [47]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [48]:
q_fc_state(q_fc_weights, maxpool_train[0])

tensor(0.95763762, requires_grad=True)

In [49]:
train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(q_fc_weights, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
    q_fc_state(q_fc_weights, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp

In [50]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False  True False False False False False False False False False False
 False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False False False False False False False False False False False False
 False False False False]


In [51]:
np.savetxt('./2_QConv2ent_QFC-State_Train.txt', train_state)
np.savetxt('./2_QConv2ent_QFC-State_Test.txt', test_state)

## Random Starting State

In [84]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 1
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 1
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 1
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)

model_random = tf.keras.Model(inputs=X, outputs=alpha_layer_0)
model_maxpool_random = tf.keras.Model(inputs=X, outputs=reshape_layer_3)

In [85]:
model_random(X_train[0:1])
model_random.weights

[<tf.Variable 'model_8/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[-0.4889698 ,  0.2380408 ,  0.09439629, -0.26716974,
           0.02344316, -0.06644684, -0.3357206 ,  0.3326074 ,
          -0.06934038]],
 
        [[ 0.3830526 ,  0.23494643,  0.41627997,  0.35118043,
          -0.42000604,  0.25128657,  0.5226568 , -0.27474615,
          -0.485173  ]]], dtype=float32)>,
 <tf.Variable 'model_8/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[-0.12407106,  0.4605006 , -0.05004978, -0.00949878,
          -0.4083493 ,  0.18536532, -0.2448183 , -0.32981884,
          -0.38940096]],
 
        [[-0.45641547, -0.41075683,  0.4251256 , -0.17653632,
           0.01394123,  0.12382543, -0.23449615,  0.47272468,
           0.31813556]]], dtype=float32)>,
 <tf.Variable 'model_8/keras_layer_4/params:0' shape=(2, 1, 9) dtype=float32, numpy=
 array([[[-0.4163184 ,  0.29198825,  0.49920654,  0.33594978,
          -0.49212807, 

In [86]:
random_weights = np.array([[[-0.4163184 ,  0.29198825,  0.49920654,  0.33594978,
          -0.49212807,  0.00343066,  0.30105686, -0.15320912,
          -0.5011647 ]],
 
        [[ 0.41882396,  0.17975801,  0.3508029 ,  0.37545007,
          -0.37378743,  0.39107925, -0.3128681 , -0.22416279,
          -0.00185567]]])

In [87]:
maxpool_train = model_maxpool_random(X_train)
maxpool_test = model_maxpool_random(X_test)

maxpool_train.shape, maxpool_test.shape

(TensorShape([40, 9]), TensorShape([40, 9]))

In [88]:
n_qubits = 1  # number of class
dev_state = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_state)
def q_fc_state(params, inputs):
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    #return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]
    return qml.expval(qml.Hermitian(density_matrix(state_labels[0]), wires=[0]))

In [89]:
q_fc_state(np.zeros((2,1,9)), maxpool_train[0])

tensor(1., requires_grad=True)

In [92]:
q_fc_state(random_weights, maxpool_train[21])

tensor(0.75178797, requires_grad=True)

In [93]:
train_state = np.zeros((len(X_train), 2), dtype=np.complex_)
test_state = np.zeros((len(X_test), 2), dtype=np.complex_)

for i in range(len(train_state)):
    
    q_fc_state(random_weights, maxpool_train[i])
    temp = np.flip(dev_state._state)
    train_state[i, :] = temp
    
    q_fc_state(random_weights, maxpool_test[i])
    temp = np.flip(dev_state._state)
    test_state[i, :] = temp

In [94]:
# sanity check

print(((np.conj(train_state) @ density_matrix(state_labels[0])) * train_state)[:, 0] > 0.5)

print(((np.conj(test_state) @ density_matrix(state_labels[0])) * test_state)[:, 0] > 0.5)

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]


In [95]:
np.savetxt('./2_QConv2ent_QFC-RandomState_Train.txt', train_state)
np.savetxt('./2_QConv2ent_QFC-RandomState_Test.txt', test_state)

# Finish

In [76]:
first_10_epoch = H.history
first_10_epoch

{'loss': [0.7249730825424194,
  0.485493928194046,
  0.2910504639148712,
  0.20750370621681213,
  0.1200886219739914,
  0.09333930909633636,
  0.09352166950702667,
  0.09991505742073059,
  0.0711403489112854,
  0.0675935298204422],
 'accuracy': [0.5249999761581421,
  0.6225000023841858,
  0.7825000286102295,
  0.8650000095367432,
  0.9449999928474426,
  0.9599999785423279,
  0.9624999761581421,
  0.9524999856948853,
  0.9750000238418579,
  0.9775000214576721],
 'val_loss': [0.6175757646560669,
  0.40504130721092224,
  0.3411727547645569,
  0.19497469067573547,
  0.11362368613481522,
  0.07933302223682404,
  0.1450268030166626,
  0.0960061326622963,
  0.09231595695018768,
  0.053687386214733124],
 'val_accuracy': [0.5,
  0.7300000190734863,
  0.7400000095367432,
  0.8700000047683716,
  0.9449999928474426,
  0.9800000190734863,
  0.925000011920929,
  0.9649999737739563,
  0.9549999833106995,
  0.9750000238418579]}

In [77]:
# initial 10 epoch
model.get_weights()

[array([[[ 0.13920915, -0.7933977 ,  0.4931736 , -0.34984022,
           0.41861725, -0.1258272 , -0.3323837 ,  1.4861933 ,
           0.14679849]],
 
        [[-0.48547882, -0.6672664 , -0.30831295,  0.31500554,
           0.21519628, -0.09552038, -0.33133912,  0.8978053 ,
          -0.38653338]]], dtype=float32),
 array([[[-0.04071528, -0.5614164 , -0.5472108 ,  0.32481748,
          -0.1586527 ,  0.06802678, -0.04312551, -1.0716503 ,
          -0.09168857]],
 
        [[ 0.2695058 , -1.5634912 ,  0.20198631, -0.20597708,
           0.06802317,  0.2522897 , -0.01191515,  0.5282674 ,
          -0.3303873 ]]], dtype=float32),
 array([[[-0.1229878 ,  0.03982117, -0.29502654, -1.2658846 ,
          -0.3401566 , -0.93464977,  1.1978221 , -0.24731389,
          -0.51143396]],
 
        [[-0.05537069, -1.3277841 , -0.7294856 , -0.740143  ,
          -0.83612764,  0.6652604 ,  0.0570471 , -0.4578703 ,
          -0.36179888]]], dtype=float32),
 array([[1.084761 , 1.0133266]], dtype=float32)]