In [1]:
# %matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

# Loading Raw Data

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train[:, 0:27, 0:27]
x_test = x_test[:, 0:27, 0:27]

In [3]:
x_train_flatten = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])/255.0
x_test_flatten = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])/255.0

In [4]:
print(x_train_flatten.shape, y_train.shape)
print(x_test_flatten.shape, y_test.shape)

(60000, 729) (60000,)
(10000, 729) (10000,)


In [5]:
x_train_0 = x_train_flatten[y_train == 0]
x_train_1 = x_train_flatten[y_train == 1]
x_train_2 = x_train_flatten[y_train == 2]
x_train_3 = x_train_flatten[y_train == 3]
x_train_4 = x_train_flatten[y_train == 4]
x_train_5 = x_train_flatten[y_train == 5]
x_train_6 = x_train_flatten[y_train == 6]
x_train_7 = x_train_flatten[y_train == 7]
x_train_8 = x_train_flatten[y_train == 8]
x_train_9 = x_train_flatten[y_train == 9]

x_train_list = [x_train_0, x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6, x_train_7, x_train_8, x_train_9]

print(x_train_0.shape)
print(x_train_1.shape)
print(x_train_2.shape)
print(x_train_3.shape)
print(x_train_4.shape)
print(x_train_5.shape)
print(x_train_6.shape)
print(x_train_7.shape)
print(x_train_8.shape)
print(x_train_9.shape)

(5923, 729)
(6742, 729)
(5958, 729)
(6131, 729)
(5842, 729)
(5421, 729)
(5918, 729)
(6265, 729)
(5851, 729)
(5949, 729)


In [6]:
x_test_0 = x_test_flatten[y_test == 0]
x_test_1 = x_test_flatten[y_test == 1]
x_test_2 = x_test_flatten[y_test == 2]
x_test_3 = x_test_flatten[y_test == 3]
x_test_4 = x_test_flatten[y_test == 4]
x_test_5 = x_test_flatten[y_test == 5]
x_test_6 = x_test_flatten[y_test == 6]
x_test_7 = x_test_flatten[y_test == 7]
x_test_8 = x_test_flatten[y_test == 8]
x_test_9 = x_test_flatten[y_test == 9]

x_test_list = [x_test_0, x_test_1, x_test_2, x_test_3, x_test_4, x_test_5, x_test_6, x_test_7, x_test_8, x_test_9]

print(x_test_0.shape)
print(x_test_1.shape)
print(x_test_2.shape)
print(x_test_3.shape)
print(x_test_4.shape)
print(x_test_5.shape)
print(x_test_6.shape)
print(x_test_7.shape)
print(x_test_8.shape)
print(x_test_9.shape)

(980, 729)
(1135, 729)
(1032, 729)
(1010, 729)
(982, 729)
(892, 729)
(958, 729)
(1028, 729)
(974, 729)
(1009, 729)


# Selecting the dataset

Output: X_train, Y_train, X_test, Y_test

In [7]:
n_train_sample_per_class = 200
n_class = 4

X_train = x_train_list[0][:n_train_sample_per_class, :]
Y_train = np.zeros((X_train.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_train = np.concatenate((X_train, x_train_list[i+1][:n_train_sample_per_class, :]), axis=0)
    Y_train[(i+1)*n_train_sample_per_class:(i+2)*n_train_sample_per_class] = i+1

X_train.shape, Y_train.shape

((800, 729), (800,))

In [8]:
n_test_sample_per_class = int(0.25*n_train_sample_per_class)

X_test = x_test_list[0][:n_test_sample_per_class, :]
Y_test = np.zeros((X_test.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_test = np.concatenate((X_test, x_test_list[i+1][:n_test_sample_per_class, :]), axis=0)
    Y_test[(i+1)*n_test_sample_per_class:(i+2)*n_test_sample_per_class] = i+1

X_test.shape, Y_test.shape

((200, 729), (200,))

# Dataset Preprocessing

In [9]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((800, 27, 27), (200, 27, 27))

In [10]:
Y_train_dict = []
for i in range(np.unique(Y_train).shape[0]):
    temp_Y = np.zeros(Y_train.shape)
    
    temp_Y[Y_train == i] = 0  # positive class
    temp_Y[Y_train != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_train_dict += [('Y' + str(i), temp_Y)]
    
Y_train_dict = dict(Y_train_dict)

In [11]:
Y_test_dict = []
for i in range(np.unique(Y_test).shape[0]):
    temp_Y = np.zeros(Y_test.shape)
    
    temp_Y[Y_test == i] = 0  # positive class
    temp_Y[Y_test != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_test_dict += [('Y' + str(i), temp_Y)]
    
Y_test_dict = dict(Y_test_dict)

In [12]:
Y_train_dict['Y1'].shape, Y_test_dict['Y0'].shape

((800, 2), (200, 2))

# Quantum

In [13]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer, GradientDescentOptimizer

qml.enable_tape()

from tensorflow.keras.utils import to_categorical

# Set a random seed
np.random.seed(2020)

In [14]:
# Define output labels as quantum state vectors
def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return state * np.conj(state).T


label_0 = [[1], [0]]
label_1 = [[0], [1]]
state_labels = [label_0, label_1]

In [15]:
n_qubits = 2
dev_fc = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs = [x, y]
        x (array[float]): 1-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]


In [16]:
dev_conv = qml.device("default.qubit", wires=3)


@qml.qnode(dev_conv)
def q_conv(conv_params, inputs):
    """A variational quantum circuit representing the Universal classifier + Conv.

    Args:
        params (array[float]): array of parameters
        x (array[float]): 2-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    # layer iteration
    for l in range(len(conv_params[0])):
        # qubit iteration
        for q in range(3):
            qml.Rot(*(conv_params[0][l][3*q:3*(q+1)] * inputs[q, 0:3] + conv_params[1][l][3*q:3*(q+1)]), wires=q)

    return [qml.expval(qml.PauliZ(j)) for j in range(3)]

In [17]:
a = np.zeros((2, 1, 9))
q_conv(a, X_train[0, 0:3, 0:3])

tensor([1., 1., 1.], requires_grad=True)

In [18]:
a = np.zeros((2, 1, 9))
q_fc(a, X_train[0, 0, 0:9])

tensor([1., 0.], requires_grad=True)

In [19]:
from keras import backend as K

# Addition Custom Layer
def add_matrix(x):
    return K.sum(x, axis=1, keepdims=True)
    
addition_layer = tf.keras.layers.Lambda(add_matrix, output_shape=(1,))

class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [20]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(3), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(3), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = addition_layer(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 1
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)

model = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])

In [21]:
for i in range(len(Y_train_dict)):
    new_key = model.layers[len(model.layers)-4+i].name
    old_key = "Y" + str(i)
    
    Y_train_dict[new_key] = Y_train_dict.pop(old_key)
    Y_test_dict[new_key] = Y_test_dict.pop(old_key)

In [22]:
Y_train_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_1': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_2': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_3': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32)}

In [23]:
Y_test_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0.

In [24]:
model(X_train[0:5, :, :])

[<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.02016014,  0.00071734],
        [-0.02037803,  0.00060614],
        [-0.02029464,  0.0006487 ],
        [-0.02023455,  0.00067937],
        [-0.02019871,  0.00069766]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[ 0.06921183, -0.00048556],
        [ 0.06901894, -0.00069632],
        [ 0.06926789, -0.00042429],
        [ 0.06918471, -0.00051519],
        [ 0.06926954, -0.00042249]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[0.0193392 , 0.00061331],
        [0.01933751, 0.00061593],
        [0.0195087 , 0.00035142],
        [0.01939072, 0.00053372],
        [0.01939507, 0.00052699]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-2.4986252e-02,  1.2285361e-04],
        [-2.5052771e-02,  8.5832369e-05],
        [-2.5053542e-02,  8.5403255e-05],
        [-2.5019446e-02,  1.0437985e-04],
        [-2.5011320e-02,  1.0890157e-04]], dtype=flo

In [25]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 27, 27)]     0                                            
__________________________________________________________________________________________________
tf.__operators__.getitem (Slici (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_1 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_2 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
______________________________________________________________________________________________

In [26]:
losses = {
    model.layers[len(model.layers)-4+0].name: "mse",
    model.layers[len(model.layers)-4+1].name: "mse",
    model.layers[len(model.layers)-4+2].name: "mse",
    model.layers[len(model.layers)-4+3].name: "mse"
}

#lossWeights = {"Y0": 1.0, "Y1": 1.0, "Y2": 1.0, "Y3": 1.0}

print(losses)

{'class_weights': 'mse', 'class_weights_1': 'mse', 'class_weights_2': 'mse', 'class_weights_3': 'mse'}


In [27]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)
model.compile(opt, loss=losses, metrics=["accuracy"])

In [28]:
cp_val_acc = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv1_QFC_valacc.hdf5",
                monitor='val_accuracy', verbose=1, save_weights_only=True, save_best_only=True, mode='max')

cp_val_loss = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv1_QFC_valloss.hdf5",
                monitor='val_loss', verbose=1, save_weights_only=True, save_best_only=True, mode='min')

In [29]:
H = model.fit(X_train, Y_train_dict, epochs=10, batch_size=32,
              validation_data=(X_test, Y_test_dict), verbose=1, initial_epoch=0,
              callbacks=[cp_val_acc, cp_val_loss])

Epoch 1/10
25/25 [==============================] - 10682s 428s/step - loss: 1.3022 - class_weights_loss: 0.3250 - class_weights_1_loss: 0.3361 - class_weights_2_loss: 0.3155 - class_weights_3_loss: 0.3256 - class_weights_accuracy: 0.7386 - class_weights_1_accuracy: 0.5496 - class_weights_2_accuracy: 0.6176 - class_weights_3_accuracy: 0.6898 - val_loss: 0.7388 - val_class_weights_loss: 0.1980 - val_class_weights_1_loss: 0.1583 - val_class_weights_2_loss: 0.1842 - val_class_weights_3_loss: 0.1983 - val_class_weights_accuracy: 0.6750 - val_class_weights_1_accuracy: 0.7250 - val_class_weights_2_accuracy: 0.7700 - val_class_weights_3_accuracy: 0.7500



Epoch 00001: val_loss improved from inf to 0.73879, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 2/10
25/25 [==============================] - 10474s 419s/step - loss: 0.7752 - class_weights_loss: 0.2073 - class_weights_1_loss: 0.1832 - class_weights_2_loss: 0.1812 - class_weights_3_loss: 0.2035 - class_weights_accuracy: 0.7017 - class_weights_1_accuracy: 0.7187 - class_weights_2_accuracy: 0.7603 - class_weights_3_accuracy: 0.7456 - val_loss: 0.6255 - val_class_weights_loss: 0.1593 - val_class_weights_1_loss: 0.1168 - val_class_weights_2_loss: 0.1838 - val_class_weights_3_loss: 0.1656 - val_class_weights_accuracy: 0.7450 - val_class_weights_1_accuracy: 0.8600 - val_class_weights_2_accuracy: 0.7300 - val_class_weights_3_accuracy: 0.7450



Epoch 00002: val_loss improved from 0.73879 to 0.62547, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 3/10
25/25 [==============================] - 10249s 410s/step - loss: 0.6543 - class_weights_loss: 0.1671 - class_weights_1_loss: 0.1350 - class_weights_2_loss: 0.1789 - class_weights_3_loss: 0.1732 - class_weights_accuracy: 0.7439 - class_weights_1_accuracy: 0.8075 - class_weights_2_accuracy: 0.7526 - class_weights_3_accuracy: 0.7738 - val_loss: 0.5328 - val_class_weights_loss: 0.1223 - val_class_weights_1_loss: 0.0855 - val_class_weights_2_loss: 0.1819 - val_class_weights_3_loss: 0.1430 - val_class_weights_accuracy: 0.8500 - val_class_weights_1_accuracy: 0.9100 - val_class_weights_2_accuracy: 0.7400 - val_class_weights_3_accuracy: 0.8000



Epoch 00003: val_loss improved from 0.62547 to 0.53281, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 4/10
25/25 [==============================] - 10072s 403s/step - loss: 0.4859 - class_weights_loss: 0.1168 - class_weights_1_loss: 0.0768 - class_weights_2_loss: 0.1706 - class_weights_3_loss: 0.1217 - class_weights_accuracy: 0.8400 - class_weights_1_accuracy: 0.9059 - class_weights_2_accuracy: 0.7663 - class_weights_3_accuracy: 0.8482 - val_loss: 0.5112 - val_class_weights_loss: 0.0829 - val_class_weights_1_loss: 0.0829 - val_class_weights_2_loss: 0.1899 - val_class_weights_3_loss: 0.1555 - val_class_weights_accuracy: 0.8950 - val_class_weights_1_accuracy: 0.9050 - val_class_weights_2_accuracy: 0.6950 - val_class_weights_3_accuracy: 0.7850



Epoch 00004: val_loss improved from 0.53281 to 0.51116, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 5/10
25/25 [==============================] - 10091s 404s/step - loss: 0.4340 - class_weights_loss: 0.0786 - class_weights_1_loss: 0.0775 - class_weights_2_loss: 0.1683 - class_weights_3_loss: 0.1095 - class_weights_accuracy: 0.9061 - class_weights_1_accuracy: 0.9234 - class_weights_2_accuracy: 0.7744 - class_weights_3_accuracy: 0.8545 - val_loss: 0.4259 - val_class_weights_loss: 0.1009 - val_class_weights_1_loss: 0.0457 - val_class_weights_2_loss: 0.1514 - val_class_weights_3_loss: 0.1279 - val_class_weights_accuracy: 0.8500 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8050 - val_class_weights_3_accuracy: 0.8050



Epoch 00005: val_loss improved from 0.51116 to 0.42594, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 6/10
25/25 [==============================] - 10110s 405s/step - loss: 0.4463 - class_weights_loss: 0.1005 - class_weights_1_loss: 0.0601 - class_weights_2_loss: 0.1658 - class_weights_3_loss: 0.1199 - class_weights_accuracy: 0.8639 - class_weights_1_accuracy: 0.9477 - class_weights_2_accuracy: 0.7632 - class_weights_3_accuracy: 0.8096 - val_loss: 0.4144 - val_class_weights_loss: 0.0784 - val_class_weights_1_loss: 0.0552 - val_class_weights_2_loss: 0.1476 - val_class_weights_3_loss: 0.1332 - val_class_weights_accuracy: 0.8700 - val_class_weights_1_accuracy: 0.9400 - val_class_weights_2_accuracy: 0.7850 - val_class_weights_3_accuracy: 0.8350



Epoch 00006: val_loss improved from 0.42594 to 0.41435, saving model to ./Model/4_QConv1_QFC_valloss.hdf5
Epoch 7/10
25/25 [==============================] - 10185s 408s/step - loss: 0.3890 - class_weights_loss: 0.0845 - class_weights_1_loss: 0.0581 - class_weights_2_loss: 0.1504 - class_weights_3_loss: 0.0959 - class_weights_accuracy: 0.8951 - class_weights_1_accuracy: 0.9528 - class_weights_2_accuracy: 0.7978 - class_weights_3_accuracy: 0.8630 - val_loss: 0.4195 - val_class_weights_loss: 0.1025 - val_class_weights_1_loss: 0.0546 - val_class_weights_2_loss: 0.1706 - val_class_weights_3_loss: 0.0917 - val_class_weights_accuracy: 0.8500 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.7450 - val_class_weights_3_accuracy: 0.8850



Epoch 00007: val_loss did not improve from 0.41435
Epoch 8/10
25/25 [==============================] - 10174s 407s/step - loss: 0.4044 - class_weights_loss: 0.0973 - class_weights_1_loss: 0.0696 - class_weights_2_loss: 0.1474 - class_weights_3_loss: 0.0901 - class_weights_accuracy: 0.8513 - class_weights_1_accuracy: 0.9283 - class_weights_2_accuracy: 0.8125 - class_weights_3_accuracy: 0.8822 - val_loss: 0.4257 - val_class_weights_loss: 0.0987 - val_class_weights_1_loss: 0.0454 - val_class_weights_2_loss: 0.1749 - val_class_weights_3_loss: 0.1066 - val_class_weights_accuracy: 0.8650 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.7350 - val_class_weights_3_accuracy: 0.8400



Epoch 00008: val_loss did not improve from 0.41435
Epoch 9/10
25/25 [==============================] - 10322s 414s/step - loss: 0.3890 - class_weights_loss: 0.0888 - class_weights_1_loss: 0.0546 - class_weights_2_loss: 0.1411 - class_weights_3_loss: 0.1045 - class_weights_accuracy: 0.8891 - class_weights_1_accuracy: 0.9542 - class_weights_2_accuracy: 0.7920 - class_weights_3_accuracy: 0.8480 - val_loss: 0.5557 - val_class_weights_loss: 0.1057 - val_class_weights_1_loss: 0.1410 - val_class_weights_2_loss: 0.1666 - val_class_weights_3_loss: 0.1424 - val_class_weights_accuracy: 0.8800 - val_class_weights_1_accuracy: 0.7700 - val_class_weights_2_accuracy: 0.7700 - val_class_weights_3_accuracy: 0.8000



Epoch 00009: val_loss did not improve from 0.41435
Epoch 10/10
25/25 [==============================] - 10411s 417s/step - loss: 0.4079 - class_weights_loss: 0.0855 - class_weights_1_loss: 0.0648 - class_weights_2_loss: 0.1552 - class_weights_3_loss: 0.1025 - class_weights_accuracy: 0.8907 - class_weights_1_accuracy: 0.9406 - class_weights_2_accuracy: 0.7775 - class_weights_3_accuracy: 0.8592 - val_loss: 0.4247 - val_class_weights_loss: 0.0804 - val_class_weights_1_loss: 0.0629 - val_class_weights_2_loss: 0.1674 - val_class_weights_3_loss: 0.1140 - val_class_weights_accuracy: 0.8950 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.7700 - val_class_weights_3_accuracy: 0.8300



Epoch 00010: val_loss did not improve from 0.41435


In [30]:
H.history

{'loss': [1.028235912322998,
  0.7406251430511475,
  0.6145067811012268,
  0.49770745635032654,
  0.42172619700431824,
  0.4250338673591614,
  0.41452789306640625,
  0.41087329387664795,
  0.393078088760376,
  0.40917015075683594],
 'class_weights_loss': [0.25758934020996094,
  0.1922397017478943,
  0.15171384811401367,
  0.10997448861598969,
  0.08719060570001602,
  0.0973159670829773,
  0.09511592984199524,
  0.10283245146274567,
  0.0877833142876625,
  0.09048928320407867],
 'class_weights_1_loss': [0.2655135989189148,
  0.16827581822872162,
  0.12089882045984268,
  0.08267521113157272,
  0.07012270390987396,
  0.06241558492183685,
  0.06121411919593811,
  0.06535360217094421,
  0.06060339882969856,
  0.061685241758823395],
 'class_weights_2_loss': [0.25084811449050903,
  0.18395966291427612,
  0.1749897599220276,
  0.18455956876277924,
  0.15906792879104614,
  0.1515231430530548,
  0.15186938643455505,
  0.1479504257440567,
  0.14770574867725372,
  0.1605766862630844],
 'class_weig

In [31]:
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.10122328, -0.00567823, -0.05245332,  0.5027749 ,
          -0.36102173,  1.5192019 ,  0.4313522 , -1.1065158 ,
          -1.3880435 ],
         [ 0.47901648,  1.640669  , -0.2413705 , -0.947364  ,
          -0.8345095 , -0.01100323,  0.53961134, -0.62476397,
           0.2589227 ]],
 
        [[-0.18951517, -0.19309627, -0.05532203, -0.4128581 ,
          -1.0657626 , -0.9807418 , -0.42666423, -0.03356916,
           0.0170973 ],
         [-0.23824558,  0.7150777 , -0.26934263, -0.27767414,
          -1.3929398 , -0.37657872, -0.579844  ,  0.04835792,
           0.06138151]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.07355112,  0.15901124,  0.460135  , -0.44399202,
          -0.31188983, -0.90428483,  0.20609224, -0.52787954,
           2.3496695 ],
         [-1.0634018 ,  0.63356036, -0.46190575,

In [40]:
# 1L QConv1, 1L QConv2, 1L QFC, no entangler at all
# 1 epoch = ... jam
8000/(60*60)

2.2222222222222223

In [28]:
26360/(60*60)

7.322222222222222

In [33]:
first_6_epoch_weights = model.weights
first_6_epoch_weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.30478922,  0.24122563,  1.2013984 ,  0.8962295 ,
           2.155613  ,  1.808066  , -0.6777786 , -1.3539367 ,
           0.46882528],
         [ 0.10804682,  0.4899469 , -1.4487113 ,  0.18007451,
           0.21117014, -0.07102177,  0.22456087,  0.19595939,
           0.620559  ]],
 
        [[ 0.08490325, -0.46300295,  0.88712513,  0.21560192,
           0.68917143, -1.3093163 ,  1.0160891 , -0.17013887,
           0.09957722],
         [ 0.08793638, -0.0810757 , -0.3338206 ,  0.5029927 ,
           0.46003294,  0.47570366, -0.18548904, -0.2648427 ,
          -0.0655445 ]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.7642950e-01,  2.3297124e+00, -7.7425838e-01,  4.8847955e-01,
           4.3419965e-02, -3.3615255e-01, -1.0063299e+00,  2.2314610e+00,
           9.1715485e-01],
         [-4.1352111e

In [34]:
first_6_epoch_hist = H.history
first_6_epoch_hist

{'loss': [0.9413223266601562,
  0.5048812627792358,
  0.4011978209018707,
  0.347080796957016,
  0.31995534896850586,
  0.29129528999328613],
 'class_weights_loss': [0.2251260131597519,
  0.1090371310710907,
  0.07864071428775787,
  0.0647929459810257,
  0.05809621885418892,
  0.056281398981809616],
 'class_weights_1_loss': [0.21691031754016876,
  0.09565035998821259,
  0.06009742617607117,
  0.043785590678453445,
  0.03979836404323578,
  0.03735021501779556],
 'class_weights_2_loss': [0.2575957775115967,
  0.16418935358524323,
  0.1520228236913681,
  0.13327646255493164,
  0.12420327216386795,
  0.10296647995710373],
 'class_weights_3_loss': [0.24169006943702698,
  0.13600443303585052,
  0.11043684929609299,
  0.10522573441267014,
  0.0978575050830841,
  0.09469721466302872],
 'class_weights_accuracy': [0.7325000166893005,
  0.862500011920929,
  0.9137499928474426,
  0.9212499856948853,
  0.9337499737739563,
  0.9449999928474426],
 'class_weights_1_accuracy': [0.7612500190734863,
  0.