In [1]:
# %matplotlib inline
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

import numpy as np

import tensorflow as tf
from tensorflow.keras.utils import to_categorical

# Loading Raw Data

In [2]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

x_train = x_train[:, 0:27, 0:27]
x_test = x_test[:, 0:27, 0:27]

In [3]:
x_train_flatten = x_train.reshape(x_train.shape[0], x_train.shape[1]*x_train.shape[2])/255.0
x_test_flatten = x_test.reshape(x_test.shape[0], x_test.shape[1]*x_test.shape[2])/255.0

In [4]:
print(x_train_flatten.shape, y_train.shape)
print(x_test_flatten.shape, y_test.shape)

(60000, 729) (60000,)
(10000, 729) (10000,)


In [5]:
x_train_0 = x_train_flatten[y_train == 0]
x_train_1 = x_train_flatten[y_train == 1]
x_train_2 = x_train_flatten[y_train == 2]
x_train_3 = x_train_flatten[y_train == 3]
x_train_4 = x_train_flatten[y_train == 4]
x_train_5 = x_train_flatten[y_train == 5]
x_train_6 = x_train_flatten[y_train == 6]
x_train_7 = x_train_flatten[y_train == 7]
x_train_8 = x_train_flatten[y_train == 8]
x_train_9 = x_train_flatten[y_train == 9]

x_train_list = [x_train_0, x_train_1, x_train_2, x_train_3, x_train_4, x_train_5, x_train_6, x_train_7, x_train_8, x_train_9]

print(x_train_0.shape)
print(x_train_1.shape)
print(x_train_2.shape)
print(x_train_3.shape)
print(x_train_4.shape)
print(x_train_5.shape)
print(x_train_6.shape)
print(x_train_7.shape)
print(x_train_8.shape)
print(x_train_9.shape)

(5923, 729)
(6742, 729)
(5958, 729)
(6131, 729)
(5842, 729)
(5421, 729)
(5918, 729)
(6265, 729)
(5851, 729)
(5949, 729)


In [6]:
x_test_0 = x_test_flatten[y_test == 0]
x_test_1 = x_test_flatten[y_test == 1]
x_test_2 = x_test_flatten[y_test == 2]
x_test_3 = x_test_flatten[y_test == 3]
x_test_4 = x_test_flatten[y_test == 4]
x_test_5 = x_test_flatten[y_test == 5]
x_test_6 = x_test_flatten[y_test == 6]
x_test_7 = x_test_flatten[y_test == 7]
x_test_8 = x_test_flatten[y_test == 8]
x_test_9 = x_test_flatten[y_test == 9]

x_test_list = [x_test_0, x_test_1, x_test_2, x_test_3, x_test_4, x_test_5, x_test_6, x_test_7, x_test_8, x_test_9]

print(x_test_0.shape)
print(x_test_1.shape)
print(x_test_2.shape)
print(x_test_3.shape)
print(x_test_4.shape)
print(x_test_5.shape)
print(x_test_6.shape)
print(x_test_7.shape)
print(x_test_8.shape)
print(x_test_9.shape)

(980, 729)
(1135, 729)
(1032, 729)
(1010, 729)
(982, 729)
(892, 729)
(958, 729)
(1028, 729)
(974, 729)
(1009, 729)


# Selecting the dataset

Output: X_train, Y_train, X_test, Y_test

In [7]:
n_train_sample_per_class = 200
n_class = 4

X_train = x_train_list[0][:n_train_sample_per_class, :]
Y_train = np.zeros((X_train.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_train = np.concatenate((X_train, x_train_list[i+1][:n_train_sample_per_class, :]), axis=0)
    Y_train[(i+1)*n_train_sample_per_class:(i+2)*n_train_sample_per_class] = i+1

X_train.shape, Y_train.shape

((800, 729), (800,))

In [8]:
n_test_sample_per_class = int(0.25*n_train_sample_per_class)

X_test = x_test_list[0][:n_test_sample_per_class, :]
Y_test = np.zeros((X_test.shape[0]*n_class,), dtype=int)

for i in range(n_class-1):
    X_test = np.concatenate((X_test, x_test_list[i+1][:n_test_sample_per_class, :]), axis=0)
    Y_test[(i+1)*n_test_sample_per_class:(i+2)*n_test_sample_per_class] = i+1

X_test.shape, Y_test.shape

((200, 729), (200,))

# Dataset Preprocessing

In [9]:
X_train = X_train.reshape(X_train.shape[0], 27, 27)
X_test = X_test.reshape(X_test.shape[0], 27, 27)

X_train.shape, X_test.shape

((800, 27, 27), (200, 27, 27))

In [10]:
Y_train_dict = []
for i in range(np.unique(Y_train).shape[0]):
    temp_Y = np.zeros(Y_train.shape)
    
    temp_Y[Y_train == i] = 0  # positive class
    temp_Y[Y_train != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_train_dict += [('Y' + str(i), temp_Y)]
    
Y_train_dict = dict(Y_train_dict)

In [11]:
Y_test_dict = []
for i in range(np.unique(Y_test).shape[0]):
    temp_Y = np.zeros(Y_test.shape)
    
    temp_Y[Y_test == i] = 0  # positive class
    temp_Y[Y_test != i] = 1  # negative class
    temp_Y = to_categorical(temp_Y)
    Y_test_dict += [('Y' + str(i), temp_Y)]
    
Y_test_dict = dict(Y_test_dict)

In [12]:
Y_train_dict['Y1'].shape, Y_test_dict['Y0'].shape

((800, 2), (200, 2))

# Quantum

In [13]:
import pennylane as qml
from pennylane import numpy as np
from pennylane.optimize import AdamOptimizer, GradientDescentOptimizer

qml.enable_tape()

from tensorflow.keras.utils import to_categorical

# Set a random seed
np.random.seed(2020)

In [14]:
# Define output labels as quantum state vectors
def density_matrix(state):
    """Calculates the density matrix representation of a state.

    Args:
        state (array[complex]): array representing a quantum state vector

    Returns:
        dm: (array[complex]): array representing the density matrix
    """
    return state * np.conj(state).T


label_0 = [[1], [0]]
label_1 = [[0], [1]]
state_labels = [label_0, label_1]

In [15]:
n_qubits = 2
dev_fc = qml.device("default.qubit", wires=n_qubits)


@qml.qnode(dev_fc)
def q_fc(params, inputs):
    """A variational quantum circuit representing the DRC.

    Args:
        params (array[float]): array of parameters
        inputs = [x, y]
        x (array[float]): 1-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    
    # layer iteration
    for l in range(len(params[0])):
        # qubit iteration
        for q in range(n_qubits):
            # gate iteration
            for g in range(int(len(inputs)/3)):
                qml.Rot(*(params[0][l][3*g:3*(g+1)] * inputs[3*g:3*(g+1)] + params[1][l][3*g:3*(g+1)]), wires=q)
    
    return [qml.expval(qml.Hermitian(density_matrix(state_labels[i]), wires=[i])) for i in range(n_qubits)]


In [16]:
dev_conv = qml.device("default.qubit", wires=9)


@qml.qnode(dev_conv)
def q_conv(conv_params, inputs):
    """A variational quantum circuit representing the Universal classifier + Conv.

    Args:
        params (array[float]): array of parameters
        x (array[float]): 2-d input vector
        y (array[float]): single output state density matrix

    Returns:
        float: fidelity between output state and input
    """
    # layer iteration
    for l in range(len(conv_params[0])):
        # RY layer
        # height iteration
        for i in range(3):
            # width iteration
            for j in range(3):
                qml.RY((conv_params[0][l][3*i+j] * inputs[i, j] + conv_params[1][l][3*i+j]), wires=(3*i+j))
    
        # entangling layer
        for i in range(9):
            if i != (9-1):
                qml.CNOT(wires=[i, i+1])

    return qml.expval(qml.PauliZ(0) @ qml.PauliZ(1) @ qml.PauliZ(2) @ qml.PauliZ(3) @ qml.PauliZ(4) @ qml.PauliZ(5) @ qml.PauliZ(6) @ qml.PauliZ(7) @ qml.PauliZ(8))

In [17]:
a = np.zeros((2, 1, 9))
q_conv(a, X_train[0, 0:3, 0:3])

tensor(1., requires_grad=True)

In [18]:
a = np.zeros((2, 1, 9))
q_fc(a, X_train[0, 0, 0:9])

tensor([1., 0.], requires_grad=True)

In [19]:
class class_weights(tf.keras.layers.Layer):
    def __init__(self):
        super(class_weights, self).__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(1, 2), dtype="float32"),
            trainable=True,
        )

    def call(self, inputs):
        return (inputs * self.w)

In [20]:
# Input image, size = 27 x 27
X = tf.keras.Input(shape=(27,27), name='Input_Layer')


# Specs for Conv
c_filter = 3
c_strides = 2


# First Quantum Conv Layer, trainable params = 18*L, output size = 13 x 13
num_conv_layer_1 = 2
q_conv_layer_1 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_1, 9)}, output_dim=(1), name='Quantum_Conv_Layer_1')
size_1 = int(1+(X.shape[1]-c_filter)/c_strides)
q_conv_layer_1_list = []
# height iteration
for i in range(size_1):
    # width iteration
    for j in range(size_1):
        temp = q_conv_layer_1(X[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_1_list += [temp]
concat_layer_1 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_1_list)
reshape_layer_1 = tf.keras.layers.Reshape((size_1, size_1))(concat_layer_1)


# Second Quantum Conv Layer, trainable params = 18*L, output size = 6 x 6
num_conv_layer_2 = 2
q_conv_layer_2 = qml.qnn.KerasLayer(q_conv, {"conv_params": (2, num_conv_layer_2, 9)}, output_dim=(1), name='Quantum_Conv_Layer_2')
size_2 = int(1+(reshape_layer_1.shape[1]-c_filter)/c_strides)
q_conv_layer_2_list = []
# height iteration
for i in range(size_2):
    # width iteration
    for j in range(size_2):
        temp = q_conv_layer_2(reshape_layer_1[:, 2*i:2*(i+1)+1, 2*j:2*(j+1)+1])
        temp = tf.keras.layers.Reshape((1,))(temp)
        q_conv_layer_2_list += [temp]
concat_layer_2 = tf.keras.layers.Concatenate(axis=1)(q_conv_layer_2_list)
reshape_layer_2 = tf.keras.layers.Reshape((size_2, size_2, 1))(concat_layer_2)


# Max Pooling Layer, output size = 9
max_pool_layer = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=None, name='Max_Pool_Layer')(reshape_layer_2)
reshape_layer_3 = tf.keras.layers.Reshape((9,))(max_pool_layer)


# Quantum FC Layer, trainable params = 18*L*n_class + 2, output size = 2
num_fc_layer = 2
q_fc_layer_0 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_1 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_2 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)
q_fc_layer_3 = qml.qnn.KerasLayer(q_fc, {"params": (2, num_fc_layer, 9)}, output_dim=2)(reshape_layer_3)

# Alpha Layer
alpha_layer_0 = class_weights()(q_fc_layer_0)
alpha_layer_1 = class_weights()(q_fc_layer_1)
alpha_layer_2 = class_weights()(q_fc_layer_2)
alpha_layer_3 = class_weights()(q_fc_layer_3)

model = tf.keras.Model(inputs=X, outputs=[alpha_layer_0, alpha_layer_1, alpha_layer_2, alpha_layer_3])

In [22]:
for i in range(len(Y_train_dict)):
    new_key = model.layers[len(model.layers)-4+i].name
    old_key = "Y" + str(i)
    
    Y_train_dict[new_key] = Y_train_dict.pop(old_key)
    Y_test_dict[new_key] = Y_test_dict.pop(old_key)

In [23]:
Y_train_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_1': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_2': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]], dtype=float32),
 'class_weights_3': array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]], dtype=float32)}

In [24]:
Y_test_dict

{'class_weights': array([[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0.

In [25]:
model(X_train[0:5, :, :])

[<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.08048891, -0.00660414],
        [-0.08039594, -0.00664691],
        [-0.08026092, -0.00670904],
        [-0.08033145, -0.00667659],
        [-0.08039791, -0.00664601]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.03183954,  0.00240379],
        [-0.03181611,  0.00241883],
        [-0.03179837,  0.00243022],
        [-0.03182641,  0.00241222],
        [-0.0318527 ,  0.00239534]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.00831538,  0.00227713],
        [-0.00831177,  0.00227918],
        [-0.00826682,  0.00230469],
        [-0.00829261,  0.00229005],
        [-0.00832056,  0.00227419]], dtype=float32)>,
 <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
 array([[-0.06207169,  0.0052766 ],
        [-0.06209119,  0.00526147],
        [-0.06223153,  0.00515261],
        [-0.06213807,  0.00522511],
        [-0.0621127 ,  0.00524479]], dtype=float32)>]

In [26]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 27, 27)]     0                                            
__________________________________________________________________________________________________
tf.__operators__.getitem (Slici (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_1 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
__________________________________________________________________________________________________
tf.__operators__.getitem_2 (Sli (None, 3, 3)         0           Input_Layer[0][0]                
______________________________________________________________________________________________

In [27]:
losses = {
    model.layers[len(model.layers)-4+0].name: "mse",
    model.layers[len(model.layers)-4+1].name: "mse",
    model.layers[len(model.layers)-4+2].name: "mse",
    model.layers[len(model.layers)-4+3].name: "mse"
}

#lossWeights = {"Y0": 1.0, "Y1": 1.0, "Y2": 1.0, "Y3": 1.0}

print(losses)

{'class_weights': 'mse', 'class_weights_1': 'mse', 'class_weights_2': 'mse', 'class_weights_3': 'mse'}


In [33]:
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.1,
    decay_steps=int(len(X_train)/32),
    decay_rate=0.95,
    staircase=True)

In [34]:
opt = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
model.compile(opt, loss=losses, metrics=["accuracy"])

In [35]:
cp_val_acc = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_2QFC_valacc.hdf5",
                monitor='val_accuracy', verbose=1, save_weights_only=True, save_best_only=True, mode='max')

cp_val_loss = tf.keras.callbacks.ModelCheckpoint(filepath="./Model/4_QConv2ent_2QFC_valloss.hdf5",
                monitor='val_loss', verbose=1, save_weights_only=True, save_best_only=True, mode='min')

In [ ]:
H = model.fit(X_train, Y_train_dict, epochs=10, batch_size=32,
              validation_data=(X_test, Y_test_dict), verbose=1, initial_epoch=0,
              callbacks=[cp_val_acc, cp_val_loss])

Epoch 1/10
25/25 [==============================] - 27009s 1080s/step - loss: 0.3399 - class_weights_loss: 0.0719 - class_weights_1_loss: 0.0581 - class_weights_2_loss: 0.1239 - class_weights_3_loss: 0.0859 - class_weights_accuracy: 0.9016 - class_weights_1_accuracy: 0.9302 - class_weights_2_accuracy: 0.8288 - class_weights_3_accuracy: 0.8985 - val_loss: 0.2675 - val_class_weights_loss: 0.0661 - val_class_weights_1_loss: 0.0466 - val_class_weights_2_loss: 0.0890 - val_class_weights_3_loss: 0.0658 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9550 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.9000



Epoch 00001: val_loss improved from inf to 0.26747, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 2/10
25/25 [==============================] - 27263s 1092s/step - loss: 0.2508 - class_weights_loss: 0.0596 - class_weights_1_loss: 0.0307 - class_weights_2_loss: 0.1071 - class_weights_3_loss: 0.0534 - class_weights_accuracy: 0.9293 - class_weights_1_accuracy: 0.9739 - class_weights_2_accuracy: 0.8588 - class_weights_3_accuracy: 0.9350 - val_loss: 0.2509 - val_class_weights_loss: 0.0675 - val_class_weights_1_loss: 0.0358 - val_class_weights_2_loss: 0.0902 - val_class_weights_3_loss: 0.0574 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9650 - val_class_weights_2_accuracy: 0.8850 - val_class_weights_3_accuracy: 0.9200



Epoch 00002: val_loss improved from 0.26747 to 0.25092, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 3/10
25/25 [==============================] - 27457s 1100s/step - loss: 0.2248 - class_weights_loss: 0.0463 - class_weights_1_loss: 0.0359 - class_weights_2_loss: 0.0884 - class_weights_3_loss: 0.0542 - class_weights_accuracy: 0.9389 - class_weights_1_accuracy: 0.9562 - class_weights_2_accuracy: 0.8953 - class_weights_3_accuracy: 0.9382 - val_loss: 0.2500 - val_class_weights_loss: 0.0577 - val_class_weights_1_loss: 0.0409 - val_class_weights_2_loss: 0.0966 - val_class_weights_3_loss: 0.0548 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8650 - val_class_weights_3_accuracy: 0.9350



Epoch 00003: val_loss improved from 0.25092 to 0.24997, saving model to ./Model/4_QConv2ent_2QFC_valloss.hdf5
Epoch 4/10
25/25 [==============================] - 26998s 1080s/step - loss: 0.2131 - class_weights_loss: 0.0384 - class_weights_1_loss: 0.0339 - class_weights_2_loss: 0.0968 - class_weights_3_loss: 0.0440 - class_weights_accuracy: 0.9605 - class_weights_1_accuracy: 0.9695 - class_weights_2_accuracy: 0.8854 - class_weights_3_accuracy: 0.9607 - val_loss: 0.2828 - val_class_weights_loss: 0.0580 - val_class_weights_1_loss: 0.0445 - val_class_weights_2_loss: 0.1025 - val_class_weights_3_loss: 0.0778 - val_class_weights_accuracy: 0.9300 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.8750 - val_class_weights_3_accuracy: 0.9100



Epoch 00004: val_loss did not improve from 0.24997
Epoch 5/10
25/25 [==============================] - 27116s 1087s/step - loss: 0.2285 - class_weights_loss: 0.0485 - class_weights_1_loss: 0.0377 - class_weights_2_loss: 0.0901 - class_weights_3_loss: 0.0523 - class_weights_accuracy: 0.9379 - class_weights_1_accuracy: 0.9670 - class_weights_2_accuracy: 0.8839 - class_weights_3_accuracy: 0.9346 - val_loss: 0.2941 - val_class_weights_loss: 0.0699 - val_class_weights_1_loss: 0.0338 - val_class_weights_2_loss: 0.1269 - val_class_weights_3_loss: 0.0635 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8350 - val_class_weights_3_accuracy: 0.9100



Epoch 00005: val_loss did not improve from 0.24997
Epoch 6/10
25/25 [==============================] - 27311s 1093s/step - loss: 0.2486 - class_weights_loss: 0.0465 - class_weights_1_loss: 0.0352 - class_weights_2_loss: 0.1094 - class_weights_3_loss: 0.0575 - class_weights_accuracy: 0.9417 - class_weights_1_accuracy: 0.9681 - class_weights_2_accuracy: 0.8745 - class_weights_3_accuracy: 0.9289 - val_loss: 0.2805 - val_class_weights_loss: 0.0688 - val_class_weights_1_loss: 0.0431 - val_class_weights_2_loss: 0.0876 - val_class_weights_3_loss: 0.0809 - val_class_weights_accuracy: 0.9200 - val_class_weights_1_accuracy: 0.9550 - val_class_weights_2_accuracy: 0.8800 - val_class_weights_3_accuracy: 0.9050



Epoch 00006: val_loss did not improve from 0.24997
Epoch 7/10
25/25 [==============================] - 27201s 1088s/step - loss: 0.2243 - class_weights_loss: 0.0505 - class_weights_1_loss: 0.0359 - class_weights_2_loss: 0.0913 - class_weights_3_loss: 0.0467 - class_weights_accuracy: 0.9440 - class_weights_1_accuracy: 0.9673 - class_weights_2_accuracy: 0.8894 - class_weights_3_accuracy: 0.9528 - val_loss: 0.2523 - val_class_weights_loss: 0.0630 - val_class_weights_1_loss: 0.0314 - val_class_weights_2_loss: 0.0976 - val_class_weights_3_loss: 0.0603 - val_class_weights_accuracy: 0.9350 - val_class_weights_1_accuracy: 0.9600 - val_class_weights_2_accuracy: 0.8700 - val_class_weights_3_accuracy: 0.9300



Epoch 00007: val_loss did not improve from 0.24997
Epoch 8/10
25/25 [==============================] - 26846s 1076s/step - loss: 0.1959 - class_weights_loss: 0.0435 - class_weights_1_loss: 0.0231 - class_weights_2_loss: 0.0802 - class_weights_3_loss: 0.0490 - class_weights_accuracy: 0.9612 - class_weights_1_accuracy: 0.9790 - class_weights_2_accuracy: 0.8961 - class_weights_3_accuracy: 0.9490 - val_loss: 0.2641 - val_class_weights_loss: 0.0573 - val_class_weights_1_loss: 0.0355 - val_class_weights_2_loss: 0.1009 - val_class_weights_3_loss: 0.0703 - val_class_weights_accuracy: 0.9550 - val_class_weights_1_accuracy: 0.9700 - val_class_weights_2_accuracy: 0.8550 - val_class_weights_3_accuracy: 0.9150



Epoch 00008: val_loss did not improve from 0.24997
Epoch 9/10
25/25 [==============================] - 27045s 1083s/step - loss: 0.1974 - class_weights_loss: 0.0409 - class_weights_1_loss: 0.0314 - class_weights_2_loss: 0.0815 - class_weights_3_loss: 0.0436 - class_weights_accuracy: 0.9536 - class_weights_1_accuracy: 0.9821 - class_weights_2_accuracy: 0.8896 - class_weights_3_accuracy: 0.9465 - val_loss: 0.2531 - val_class_weights_loss: 0.0580 - val_class_weights_1_loss: 0.0449 - val_class_weights_2_loss: 0.0933 - val_class_weights_3_loss: 0.0569 - val_class_weights_accuracy: 0.9250 - val_class_weights_1_accuracy: 0.9500 - val_class_weights_2_accuracy: 0.8750 - val_class_weights_3_accuracy: 0.9150



Epoch 00009: val_loss did not improve from 0.24997
Epoch 10/10
14/25 [===============>..............] - ETA: 3:12:50 - loss: 0.1990 - class_weights_loss: 0.0539 - class_weights_1_loss: 0.0268 - class_weights_2_loss: 0.0809 - class_weights_3_loss: 0.0374 - class_weights_accuracy: 0.9506 - class_weights_1_accuracy: 0.9713 - class_weights_2_accuracy: 0.8974 - class_weights_3_accuracy: 0.9575

In [31]:
H.history

{'loss': [1.0111608505249023,
  0.6868469715118408,
  0.5057929158210754,
  0.44260281324386597,
  0.35056832432746887,
  0.2968459129333496,
  0.2924039363861084,
  0.2602747976779938,
  0.26590603590011597,
  0.2575048506259918],
 'class_weights_loss': [0.26925164461135864,
  0.15809020400047302,
  0.08490398526191711,
  0.0776936411857605,
  0.06354520469903946,
  0.05990614369511604,
  0.05566360056400299,
  0.056557122617959976,
  0.0627477765083313,
  0.057271718978881836],
 'class_weights_1_loss': [0.24753987789154053,
  0.1477098912000656,
  0.08074972778558731,
  0.07177780568599701,
  0.046477146446704865,
  0.04214911535382271,
  0.05117877572774887,
  0.04142901301383972,
  0.03364543616771698,
  0.04256885126233101],
 'class_weights_2_loss': [0.2458696812391281,
  0.18835708498954773,
  0.16963106393814087,
  0.15835900604724884,
  0.12704524397850037,
  0.11556874215602875,
  0.10782639682292938,
  0.10440581291913986,
  0.102692611515522,
  0.09769731760025024],
 'class_

In [32]:
model.weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[-0.204333  , -0.9065615 ,  0.40738553, -1.1753407 ,
           0.9621245 ,  2.018857  , -0.3183474 ,  0.26782325,
           0.72603637],
         [ 0.10142553,  0.00255257, -0.7550016 , -0.5161239 ,
          -0.7630532 ,  0.03949594, -0.3264697 , -0.29303998,
           0.5397937 ]],
 
        [[ 1.7459589 ,  2.444865  ,  1.7272474 , -1.0620315 ,
           0.0189265 ,  1.1139463 , -0.20810643, -0.2684929 ,
           0.32006234],
         [ 1.3082465 , -0.13904944, -0.5299284 , -0.08237645,
          -0.13254017,  0.35362953,  0.39849976,  0.22489822,
           0.40491554]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.6681657 , -2.0086706 , -1.4954917 , -1.7829584 ,
           1.8330503 , -0.31931466, -3.97961   ,  0.24756432,
           0.36602587],
         [ 0.998142  ,  0.4393435 , -0.7992056 ,

In [40]:
# 1L QConv1, 1L QConv2, 1L QFC, no entangler at all
# 1 epoch = ... jam
8000/(60*60)

2.2222222222222223

In [28]:
26360/(60*60)

7.322222222222222

In [33]:
first_6_epoch_weights = model.weights
first_6_epoch_weights

[<tf.Variable 'model/Quantum_Conv_Layer_1/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 0.30478922,  0.24122563,  1.2013984 ,  0.8962295 ,
           2.155613  ,  1.808066  , -0.6777786 , -1.3539367 ,
           0.46882528],
         [ 0.10804682,  0.4899469 , -1.4487113 ,  0.18007451,
           0.21117014, -0.07102177,  0.22456087,  0.19595939,
           0.620559  ]],
 
        [[ 0.08490325, -0.46300295,  0.88712513,  0.21560192,
           0.68917143, -1.3093163 ,  1.0160891 , -0.17013887,
           0.09957722],
         [ 0.08793638, -0.0810757 , -0.3338206 ,  0.5029927 ,
           0.46003294,  0.47570366, -0.18548904, -0.2648427 ,
          -0.0655445 ]]], dtype=float32)>,
 <tf.Variable 'model/Quantum_Conv_Layer_2/conv_params:0' shape=(2, 2, 9) dtype=float32, numpy=
 array([[[ 2.7642950e-01,  2.3297124e+00, -7.7425838e-01,  4.8847955e-01,
           4.3419965e-02, -3.3615255e-01, -1.0063299e+00,  2.2314610e+00,
           9.1715485e-01],
         [-4.1352111e

In [34]:
first_6_epoch_hist = H.history
first_6_epoch_hist

{'loss': [0.9413223266601562,
  0.5048812627792358,
  0.4011978209018707,
  0.347080796957016,
  0.31995534896850586,
  0.29129528999328613],
 'class_weights_loss': [0.2251260131597519,
  0.1090371310710907,
  0.07864071428775787,
  0.0647929459810257,
  0.05809621885418892,
  0.056281398981809616],
 'class_weights_1_loss': [0.21691031754016876,
  0.09565035998821259,
  0.06009742617607117,
  0.043785590678453445,
  0.03979836404323578,
  0.03735021501779556],
 'class_weights_2_loss': [0.2575957775115967,
  0.16418935358524323,
  0.1520228236913681,
  0.13327646255493164,
  0.12420327216386795,
  0.10296647995710373],
 'class_weights_3_loss': [0.24169006943702698,
  0.13600443303585052,
  0.11043684929609299,
  0.10522573441267014,
  0.0978575050830841,
  0.09469721466302872],
 'class_weights_accuracy': [0.7325000166893005,
  0.862500011920929,
  0.9137499928474426,
  0.9212499856948853,
  0.9337499737739563,
  0.9449999928474426],
 'class_weights_1_accuracy': [0.7612500190734863,
  0.