In [1]:
import tensorflow as tf
import numpy as np

In [17]:
y_true = np.array([[1., 0.], [0., 1.]])
y_pred = np.array([[0.6, 0.1], [0.1, 0.6]])
# Using 'auto'/'sum_over_batch_size' reduction type.  
mse = tf.keras.losses.mean_squared_error(y_true, y_pred)
bce = tf.keras.losses.BinaryCrossentropy()
bce(y_true, y_pred), mse

(<tf.Tensor: shape=(), dtype=float64, numpy=0.3080929219722748>,
 <tf.Tensor: shape=(2,), dtype=float64, numpy=array([0.085, 0.085])>)

In [15]:
import keras.backend as K

# def custom_loss(y_true, y_pred):
#     return K.sum(((y_true.shape[1]-2)*y_true+1)*K.square(y_true-y_pred))/len(y_true)

def custom_loss(y_true, y_pred):
    return K.sum(K.square(y_true-y_pred))/len(y_true)

In [16]:
custom_loss(y_true, y_pred)

<tf.Tensor: shape=(), dtype=float64, numpy=0.17000000000000004>

In [83]:
a = np.array([[1, 2, 3], [3, 5, 6], [7, 8, 9]])
a = a.reshape(1, 3, 3, 1)
a = np.concatenate((a,a), axis=0)
a.shape

(2, 3, 3, 1)

In [84]:
a_inputs = tf.keras.Input(shape=(3,3,1))
batchnorm = tf.keras.layers.BatchNormalization()(a_inputs)

model = tf.keras.Model(inputs=a_inputs, outputs=batchnorm)

In [85]:
model(a)

<tf.Tensor: shape=(2, 3, 3, 1), dtype=float32, numpy=
array([[[[0.9995004],
         [1.9990008],
         [2.9985013]],

        [[2.9985013],
         [4.997502 ],
         [5.9970026]],

        [[6.996503 ],
         [7.996003 ],
         [8.995503 ]]],


       [[[0.9995004],
         [1.9990008],
         [2.9985013]],

        [[2.9985013],
         [4.997502 ],
         [5.9970026]],

        [[6.996503 ],
         [7.996003 ],
         [8.995503 ]]]], dtype=float32)>

In [86]:
model.weights

[<tf.Variable 'batch_normalization_3/gamma:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Variable 'batch_normalization_3/beta:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_3/moving_mean:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>,
 <tf.Variable 'batch_normalization_3/moving_variance:0' shape=(1,) dtype=float32, numpy=array([1.], dtype=float32)>]

In [2]:
mse = tf.keras.losses.MeanSquaredError()

In [65]:
a = np.array([[1.1, 0.1, 0.1, 0.1], [1.1, 0.1, 0.1, 0.1]])
b = np.array([[1, 0, 0, 0], [1, 0, 0, 0]])

In [21]:
mse(a, b).numpy()

0

In [18]:
y_pred = [[1., 1.]]
y_true = [[0., 1.]]

In [19]:
mse(y_pred, y_true).numpy()

0.5

In [66]:
import keras.backend as K

def custom_loss(y_true, y_pred):
    return K.sum(((y_true.shape[1]-2)*y_true+1)*K.square(y_true-y_pred))/len(y_true)

In [67]:
custom_loss(b,a)

<tf.Tensor: shape=(), dtype=float64, numpy=0.06000000000000006>

In [64]:
np.sum(((b.shape[1]-2)*b+1)*((b-a))**2)/2

0.3333333333333333

In [51]:
(b-a)

array([[ 0.        , -0.33333333, -0.33333333, -0.33333333],
       [ 0.        , -0.33333333, -0.33333333, -0.33333333]])